export const NEW_MOVIES = [
  { text: "من هو المخرج الذي أخرج فيلم Titanic و Avatar؟", correctAnswer: "جيمس كاميرون", wrongOptions: ["ستيفن سبيلبرغ", "كريستوفر نولان", "مارتن سكورسيزي"] },
  { text: "أي فيلم من أفلام مارفل كان الأعلى إيرادات على الإطلاق وقت عرضه؟", correctAnswer: "Avengers: Endgame", wrongOptions: ["Infinity War", "Black Panther", "The Avengers"] },
  { text: "من الذي لعب دور الجوكر في فيلم The Dark Knight وحاز على أوسكار بعد وفاته؟", correctAnswer: "هيث ليدجر", wrongOptions: ["واكين فينكس", "جاك نيكلسون", "جاريد ليتو"] },
  { text: "ما اسم بطل في سلسلة أفلام The Matrix؟", correctAnswer: "نيو", wrongOptions: ["مورفيوس", "ترينيتي", "سميث"] },
  { text: "ما هو اسم الساحر الشرير في سلسلة هاري بوتر؟", correctAnswer: "فولدمورت", wrongOptions: ["سناب", "مالفوي", "غريندلوالد"] },
  { text: "في فيلم Forrest Gump، ماذا تقول والدة فورست عن الحياة؟", correctAnswer: "إنها مثل صندوق الشوكولاتة", wrongOptions: ["إنها مثل الريح", "إنها كرحلة قارب", "إنها لعبة شطرنج"] },
  { text: "أي فيلم عربي أخرجته نادين لبكي ورشح للأوسكار؟", correctAnswer: "كفرناحوم", wrongOptions: ["سكر بنات", "وهلّق لوين؟", "المصير"] },
  { text: "من هو الممثل الذي قام بدور جاك سبارو في أفلام قراصنة الكاريبي؟", correctAnswer: "جوني ديب", wrongOptions: ["توم كروز", "براد بيت", "ليوناردو دي كابريو"] },
  { text: "ما فيلم ديزني الذي تدور أحداثه حول فتاة تبحث عن أسلافها في العالم الآخر وتعزف الموسيقى؟", correctAnswer: "Coco", wrongOptions: ["Moana", "Encanto", "Soul"] },
  { text: "في أي فيلم يظهر الـ T-Rex والديناصورات في حديقة حديثة؟", correctAnswer: "الحديقة الجوراسية", wrongOptions: ["عالم الوحوش", "غودزيلا", "كينغ كونغ"] },
  { text: "من هو الممثل الذي لعب دور 'Iron Man' الرجل الحديدي في عالم مارفل؟", correctAnswer: "روبرت داوني جونيور", wrongOptions: ["كريس إيفانز", "كريس هيمسوورث", "مارك رافالو"] },
  { text: "ما هو الفيلم الكوري الجنوبي الذي فاز بأوسكار أفضل فيلم في 2020؟", correctAnswer: "Parasite", wrongOptions: ["Minari", "Train to Busan", "Oldboy"] },
  { text: "ما هي السلسلة التي تتضمن أفلام (The Fellowship of the Ring)؟", correctAnswer: "سيد الخواتم", wrongOptions: ["الهوبيت", "هاري بوتر", "صراع العروش"] },
  { text: "في أي فيلم يخوض الأبطال رحلة إلى أحلام الناس لسرقة الأفكار؟", correctAnswer: "Inception", wrongOptions: ["Interstellar", "Tenet", "The Prestige"] },
  { text: "ما اسم الأسد الصغير في فيلم The Lion King؟", correctAnswer: "سيمبا", wrongOptions: ["موفاسا", "سكار", "نالا"] },
  { text: "أي ممثل أدى دور 'جون ويك' القاتل المحترف؟", correctAnswer: "كيانو ريفز", wrongOptions: ["توم هانكس", "ماثيو ماكونهي", "توم كروز"] },
  { text: "فيلم خيال علمي من إخراج نولان، يطمح لإنقاذ البشرية عبر السفر في ثقب دودي بالفضائية؟", correctAnswer: "Interstellar", wrongOptions: ["Gravity", "The Martian", "Apollo 13"] },
  { text: "من هي بطلة سلسلة أفلام Hunger Games؟", correctAnswer: "جينيفر لورنس", wrongOptions: ["إيما ستون", "سكارليت جوهانسون", "كريستين ستيوارت"] },
  { text: "أي فيلم يعتبر أول فيلم رسوم متحركة طويل بالكامل من إنتاج بيكسار؟", correctAnswer: "Toy Story", wrongOptions: ["A Bug's Life", "Monsters, Inc.", "Finding Nemo"] },
  { text: "ما الكلمة التي لا تكف شخصية غروت (Groot) عن قولها باستمرار؟", correctAnswer: "I am Groot", wrongOptions: ["Hello", "Save the Galaxy", "Tree"] },
  { text: "من أخرج فيلم Pulp Fiction؟", correctAnswer: "كوينتن تارانتينو", wrongOptions: ["مارتن سكورسيزي", "ريدلي سكوت", "ديفيد فينشر"] },
  { text: "في سلسلة حرب النجوم (Star Wars)، ما اسم الشرير المقنع الأشهر بعبارة 'I am your father'؟", correctAnswer: "دارث فيدر", wrongOptions: ["بالباتين", "كايلو رين", "جروغو"] },
  { text: "الممثل الفائز بأوسكار عن دوره كـ عالم الفيزياء أوبنهايمر؟", correctAnswer: "كيليان مورفي", wrongOptions: ["مات ديمون", "روبرت داوني جونيور", "كريستيان بيل"] },
  { text: "في فيلم 'Home Alone'، ما اسم الطفل الذي ينساه أهله؟", correctAnswer: "كيفن", wrongOptions: ["أليكس", "تومي", "بيتر"] },
  { text: "من هي البطلة الخارقة في فيلم 'Wonder Woman' لعام 2017؟", correctAnswer: "غال غادوت", wrongOptions: ["مارغوت روبي", "بري لارسون", "ساندرا بولوك"] },
  { text: "في سلسلة 'Fast & Furious'، ما هو اسم شخصية فين ديزل؟", correctAnswer: "دومينيك توريتو", wrongOptions: ["برايان أوكونر", "هوبس", "هان"] },
  { text: "ما الفيلم الذي يشارك فيه ويل سميث ومارتن لورنس كشرطيين في ميامي؟", correctAnswer: "Bad Boys", wrongOptions: ["Men in Black", "Rush Hour", "Lethal Weapon"] },
  { text: "في فيلم 'Up' من استوديوهات بيكسار، ماذا استخدم البطل لرفع منزله الطائر؟", correctAnswer: "مئات البالونات", wrongOptions: ["مروحة عملاقة", "أجنحة طائرة", "سحر قديم"] },
  { text: "أي من هؤلاء الممثلين لم يلعب دور باتمان في فيلم واقعي كامل؟", correctAnswer: "توم هاردي", wrongOptions: ["روبرت باتينسون", "בן أفليك", "كريستيان بيل"] },
  { text: "من هو الروبوت الذهبي الهزلي المرافق لـ R2-D2 في سلسلة حرب النجوم؟", correctAnswer: "C-3PO", wrongOptions: ["BB-8", "Wall-E", "T-800"] },
  { text: "ما الفيلم الذي تدور أحداثه حول مدينة للحيوانات المتكلمة وتعمل بها أرنبة כشرطية؟", correctAnswer: "Zootopia", wrongOptions: ["Madagascar", "Kung Fu Panda", "Ice Age"] },
  { text: "فيلم يروي قصة الملاكم 'روكي بالبوا'، من هو الكاتب والبطل؟", correctAnswer: "سيلفستر ستالون", wrongOptions: ["أرنولد شوارزنيجر", "بروس ويليس", "جان كلود فان دام"] },
  { text: "ما الفيلم المصري الشهير الذي يروي قصة الشاب الذي يتوه في الصين؟", correctAnswer: "فول الصين العظيم", wrongOptions: ["صعيدي في الجامعة الأمريكية", "همام في أمستردام", "الناظر"] },
  { text: "من هو المخرج المصري العالمي الذي أخرج فيلم 'الرسالة' و'عمر المختار'؟", correctAnswer: "مصطفى العقاد", wrongOptions: ["يوسف شاهين", "محمد خان", "داود عبد السيد"] },
  { text: "ما اسم مدرسة السحر التي يدرس فيها هاري بوتر؟", correctAnswer: "هوجورتس", wrongOptions: ["أكاديمية السحر", "كاميلوت", "أرض نورن"] },
  { text: "في أي فيلم نجد الشخصيات: شريك، فيونا، والحمار؟", correctAnswer: "Shrek", wrongOptions: ["Ice Age", "Tangled", "Brave"] },
  { text: "ما هي الرياضة الحاضرة بقوة في أفلام الكابتن ماجد أو أفلام الكوع الذهبي لستيفن تشو؟", correctAnswer: "كرة القدم (مع خلطة شاولين)", wrongOptions: ["التنس", "كرة السلة", "الفنون القتالية فقط"] },
  { text: "من هو بطل سلسلة أفلام المهمة المستحيلة (إيثان هانت)؟", correctAnswer: "توم كروز", wrongOptions: ["براد بيت", "توم هانكس", "مات ديمون"] },
  { text: "ما هو فيلم الأنمي الياباني الأعلى إيرادات (أخرجه ماكوتو شينكاي عام 2016)؟", correctAnswer: "Your Name (Kimi no Na wa)", wrongOptions: ["Spirited Away", "Demon Slayer: Mugen Train", "Weathering with You"] },
  { text: "من بطل فيلم الجريمة Scarface بشخصية 'توني مونتانا'؟", correctAnswer: "آل باتشينو", wrongOptions: ["روبرت دي نيرو", "مارلون براندو", "جو بيشي"] },
  { text: "أي فيلم رعب من روايات ستيفن كينغ يظهر فيه مهرج مرعب يسمى بينيوايز؟", correctAnswer: "IT", wrongOptions: ["The Shining", "Pet Sematary", "Carrie"] },
  { text: "ما هو السيف الشهير الخاص بمقاتلي الجيداي في سلسلة أفلام Star Wars؟", correctAnswer: "سيف الليزر (Lightsaber)", wrongOptions: ["سيف النور", "الباندينور", "نصل الطاقة"] },
  { text: "ما اسم الأميرة في فيلم دیزني التي لديها شعر سحري طويل جداً؟", correctAnswer: "رابونزل", wrongOptions: ["سنو وايت", "سندريلا", "آريل"] },
  { text: "في فيلم 'The Godfather' (الأب الروحي)، من الذي كان زعيم العائلة في الجزء الأول؟", correctAnswer: "فيتو كورليوني", wrongOptions: ["مايكل كورليوني", "سوني كورليوني", "توم هاغن"] },
  { text: "فيلم أكشن شهير يتحدث عن سيارات تتحول إلى آليين محاربين عملاقة؟", correctAnswer: "Transformers", wrongOptions: ["Pacific Rim", "Real Steel", "Power Rangers"] }
];
