export const NEW_MOVIES = [
  { text: "من بطل فيلم جون ويك (John Wick)؟", correctAnswer: "كيانو ريفز", wrongOptions: ["توم كروز", "براد بيت", "توم هاردي"] },
  { text: "أي فيلم فاز بأوسكار أفضل فيلم في 2020 وأصبح أول فيلم غير ناطق بالإنجليزية يحقق ذلك؟", correctAnswer: "Parasite", wrongOptions: ["1917", "Joker", "Roma"] },
  { text: "من لَعِب دور 'دون فيتو كورليوني' في فيلم The Godfather (1972)؟", correctAnswer: "مارلون براندو", wrongOptions: ["آل باتشينو", "روبرت دي نيرو", "جو بيشي"] },
  { text: "ما اسم المدينة التي يحميها باتمان؟", correctAnswer: "غوثام", wrongOptions: ["متروبوليس", "سنترال سيتي", "نيويورك"] },
  { text: "فيلم 'شوشانك ريديمبشن' (The Shawshank Redemption) صدر في أي عام؟", correctAnswer: "1994", wrongOptions: ["1999", "1990", "1997"] },
  { text: "من أخرج ثلاثية The Dark Knight؟", correctAnswer: "كريستوفر نولان", wrongOptions: ["زاك سنايدر", "ستيفن سبيلبيرغ", "مارتن سكورسيزي"] },
  { text: "من هو أول ممثل جسد سبايدرمان في السلسلة السينمائية الحديثة (2002)؟", correctAnswer: "توبي ماغواير", wrongOptions: ["توم هولاند", "أندرو غارفيلد", "جيك جيلنهال"] },
  { text: "ما اسم شخصية الذكاء الاصطناعي في فيلم Interstellar؟", correctAnswer: "TARS", wrongOptions: ["HAL 9000", "JARVIS", "SKYNET"] },
  { text: "من هي بطلة سلسلة أفلام The Hunger Games؟", correctAnswer: "جينيفر لورانس", wrongOptions: ["إيما ستون", "سكارليت جوهانسون", "مارجو روبي"] },
  { text: "في أي فيلم قال البطل الجملة الشهيرة: 'I am your father'؟", correctAnswer: "Star Wars: The Empire Strikes Back", wrongOptions: ["Star Trek", "The Lord of the Rings", "The Terminator"] },
  { text: "من هو مخرج فيلم تايتانيك 1997؟", correctAnswer: "جيمس كاميرون", wrongOptions: ["ستيفن سبيلبيرغ", "ريدلي سكوت", "جورج لوكاس"] },
  { text: "في أي فيلم تظهر شخصية 'هاري بوتر' لأول مرة؟", correctAnswer: "Harry Potter and the Sorcerer's Stone", wrongOptions: ["The Chamber of Secrets", "The Prisoner of Azkaban", "The Goblet of Fire"] },
  { text: "ما هو اسم شخصية جوني ديب في سلسلة أفلام قراصنة الكاريبي؟", correctAnswer: "جاك سبارو", wrongOptions: ["ويلي ونكا", "إدوارد مقصات", "ماد هاتر"] },
  { text: "أي فيلم أنيميشن عن سمكة ضاعت في المحيط ويبحث عنها والدها؟", correctAnswer: "Finding Nemo", wrongOptions: ["Shark Tale", "Toy Story", "Up"] },
  { text: "من لعب شخصية توني ستارك في عالم مارفل السينمائي؟", correctAnswer: "روبرت داوني جونيور", wrongOptions: ["كريس إيفانز", "مارك رافالو", "بيندكت كامبرباتش"] },
  { text: "ما هو الفيلم الذي يتميز بمصطلح 'القاعدة الأولى: لا تتحدث عن...'؟", correctAnswer: "Fight Club", wrongOptions: ["The Matrix", "Pulp Fiction", "Inception"] },
  { text: "من المخرج المشهور بأفلام الرعب والغموض مثل The Sixth Sense؟", correctAnswer: "إم نايت شيامالان", wrongOptions: ["جيمس وان", "جوردان بيل", "ديفيد فينشر"] },
  { text: "أي شخصية شريرة في مارفل جمعت الأحجار اللانهائية؟", correctAnswer: "ثانوس", wrongOptions: ["لوكي", "ألترون", "رونان"] }
];
