export const DYNAMIC_COUNTRIES = [
  { code: 'sa', name: 'السعودية', capital: 'الرياض', currency: 'الريال', continent: 'آسيا' },
  { code: 'eg', name: 'مصر', capital: 'القاهرة', currency: 'الجنيه', continent: 'أفريقيا' },
  { code: 'ae', name: 'الإمارات', capital: 'أبو ظبي', currency: 'الدرهم', continent: 'آسيا' },
  { code: 'dz', name: 'الجزائر', capital: 'الجزائر', currency: 'الدينار', continent: 'أفريقيا' },
  { code: 'ma', name: 'المغرب', capital: 'الرباط', currency: 'الدرهم', continent: 'أفريقيا' },
  { code: 'iq', name: 'العراق', capital: 'بغداد', currency: 'الدينار', continent: 'آسيا' },
  { code: 'sy', name: 'سوريا', capital: 'دمشق', currency: 'الليرة', continent: 'آسيا' },
  { code: 'ye', name: 'اليمن', capital: 'صنعاء', currency: 'الريال', continent: 'آسيا' },
  { code: 'tn', name: 'تونس', capital: 'تونس', currency: 'الدينار', continent: 'أفريقيا' },
  { code: 'jo', name: 'الأردن', capital: 'عمان', currency: 'الدينار', continent: 'آسيا' },
  { code: 'lb', name: 'لبنان', capital: 'بيروت', currency: 'الليرة', continent: 'آسيا' },
  { code: 'qa', name: 'قطر', capital: 'الدوحة', currency: 'الريال', continent: 'آسيا' },
  { code: 'kw', name: 'الكويت', capital: 'الكويت', currency: 'الدينار', continent: 'آسيا' },
  { code: 'bh', name: 'البحرين', capital: 'المنامة', currency: 'الدينار', continent: 'آسيا' },
  { code: 'om', name: 'عُمان', capital: 'مسقط', currency: 'الريال', continent: 'آسيا' },
  { code: 'sd', name: 'السودان', capital: 'الخرطوم', currency: 'الجنيه', continent: 'أفريقيا' },
  { code: 'ly', name: 'ليبيا', capital: 'طرابلس', currency: 'الدينار', continent: 'أفريقيا' },
  { code: 'ps', name: 'فلسطين', capital: 'القدس', currency: 'الشيكل/الدينار', continent: 'آسيا' },
  { code: 'mr', name: 'موريتانيا', capital: 'نواكشوط', currency: 'الأوقية', continent: 'أفريقيا' },
  { code: 'so', name: 'الصومال', capital: 'مقدیشو', currency: 'الشلن', continent: 'أفريقيا' },
  { code: 'us', name: 'الولايات المتحدة', capital: 'واشنطن', currency: 'الدولار', continent: 'أمريكا الشمالية' },
  { code: 'gb', name: 'بريطانيا', capital: 'لندن', currency: 'الجنيه الإسترليني', continent: 'أوروبا' },
  { code: 'fr', name: 'فرنسا', capital: 'باريس', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'de', name: 'ألمانيا', capital: 'برلين', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'it', name: 'إيطاليا', capital: 'روما', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'es', name: 'إسبانيا', capital: 'مدريد', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'ru', name: 'روسيا', capital: 'موسكو', currency: 'الروبل', continent: 'أوروبا وآسيا' },
  { code: 'cn', name: 'الصين', capital: 'بكين', currency: 'اليوان', continent: 'آسيا' },
  { code: 'jp', name: 'اليابان', capital: 'طوكيو', currency: 'الين', continent: 'آسيا' },
  { code: 'kr', name: 'كوريا الجنوبية', capital: 'سول', currency: 'الوون', continent: 'آسيا' },
  { code: 'in', name: 'الهند', capital: 'نيودلهي', currency: 'الروبية', continent: 'آسيا' },
  { code: 'br', name: 'البرازيل', capital: 'برازيليا', currency: 'الريال', continent: 'أمريكا الجنوبية' },
  { code: 'ar', name: 'الأرجنتين', capital: 'بوينس آيرس', currency: 'البيزو', continent: 'أمريكا الجنوبية' },
  { code: 'tr', name: 'تركيا', capital: 'أنقرة', currency: 'الليرة', continent: 'أوروبا وآسيا' },
  { code: 'mx', name: 'المكسيك', capital: 'مكسيكو سيتي', currency: 'البيزو', continent: 'أمريكا الشمالية' },
  { code: 'ca', name: 'كندا', capital: 'أوتاوا', currency: 'الدولار الكندي', continent: 'أمريكا الشمالية' },
  { code: 'au', name: 'أستراليا', capital: 'كانبرا', currency: 'الدولار الأسترالي', continent: 'أوقيانوسيا' },
  { code: 'za', name: 'جنوب أفريقيا', capital: 'بريتوريا', currency: 'الراند', continent: 'أفريقيا' },
  { code: 'ng', name: 'نيجيريا', capital: 'أبوجا', currency: 'النايرا', continent: 'أفريقيا' },
  { code: 'ir', name: 'إيران', capital: 'طهران', currency: 'الريال', continent: 'آسيا' },
  { code: 'pk', name: 'باكستان', capital: 'إسلام آباد', currency: 'الروبية', continent: 'آسيا' },
  { code: 'id', name: 'إندونيسيا', capital: 'جاكرتا', currency: 'الروبية', continent: 'آسيا' },
  { code: 'my', name: 'ماليزيا', capital: 'كوالالمبور', currency: 'الرينغيت', continent: 'آسيا' },
  { code: 'sg', name: 'سنغافورة', capital: 'سنغافورة', currency: 'الدولار', continent: 'آسيا' },
  { code: 'se', name: 'السويد', capital: 'ستوكهولم', currency: 'الكرونة', continent: 'أوروبا' },
  { code: 'no', name: 'النرويج', capital: 'أوسلو', currency: 'الكرونة', continent: 'أوروبا' },
  { code: 'fi', name: 'فنلندا', capital: 'هلسنكي', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'dk', name: 'الدنمارك', capital: 'كوبنهاجن', currency: 'الكرونة', continent: 'أوروبا' },
  { code: 'nl', name: 'هولندا', capital: 'أمستردام', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'be', name: 'بلجيكا', capital: 'بروكسل', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'ch', name: 'سويسرا', capital: 'بيرن', currency: 'الفرنك', continent: 'أوروبا' },
  { code: 'at', name: 'النمسا', capital: 'فيينا', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'gr', name: 'اليونان', capital: 'أثينا', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'pt', name: 'البرتغال', capital: 'لشبونة', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'ie', name: 'أيرلندا', capital: 'دبلن', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'nz', name: 'نيوزيلندا', capital: 'ويلينغتون', currency: 'الدولار', continent: 'أوقيانوسيا' },
  { code: 've', name: 'فنزويلا', capital: 'كاراكاس', currency: 'البوليفار', continent: 'أمريكا الجنوبية' },
  { code: 'co', name: 'كولومبيا', capital: 'بوغوتا', currency: 'البيزو', continent: 'أمريكا الجنوبية' },
  { code: 'cl', name: 'تشيلي', capital: 'سانتياغو', currency: 'البيزو', continent: 'أمريكا الجنوبية' },
  { code: 'pe', name: 'بيرو', capital: 'ليما', currency: 'السول', continent: 'أمريكا الجنوبية' },
  { code: 'uy', name: 'أوروغواي', capital: 'مونتيفيديو', currency: 'البيزو', continent: 'أمريكا الجنوبية' },
  { code: 'py', name: 'باراغواي', capital: 'أسونسيون', currency: 'الغواراني', continent: 'أمريكا الجنوبية' },
  { code: 'bo', name: 'بوليفيا', capital: 'سوكريه', currency: 'البوليفاريانو', continent: 'أمريكا الجنوبية' },
  { code: 'ec', name: 'الإكوادور', capital: 'كيتو', currency: 'الدولار', continent: 'أمريكا الجنوبية' },
  { code: 'ua', name: 'أوكرانيا', capital: 'كييف', currency: 'الهريفنيا', continent: 'أوروبا' },
  { code: 'pl', name: 'بولندا', capital: 'وارسو', currency: 'الزلوتي', continent: 'أوروبا' },
  { code: 'ro', name: 'رومانيا', capital: 'بوخارست', currency: 'الليو', continent: 'أوروبا' },
  { code: 'cz', name: 'التشيك', capital: 'براغ', currency: 'الكرونة', continent: 'أوروبا' },
  { code: 'hu', name: 'المجر', capital: 'بودابست', currency: 'الفورنت', continent: 'أوروبا' },
  { code: 'bg', name: 'بلغاريا', capital: 'صوفيا', currency: 'الليف', continent: 'أوروبا' },
  { code: 'rs', name: 'صربيا', capital: 'بلجراد', currency: 'الدينار', continent: 'أوروبا' },
  { code: 'hr', name: 'كرواتيا', capital: 'زغرب', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'ba', name: 'البوسنة', capital: 'سراييفو', currency: 'المارك', continent: 'أوروبا' },
  { code: 'al', name: 'ألبانيا', capital: 'تيرانا', currency: 'الليك', continent: 'أوروبا' },
  { code: 'mk', name: 'مقدونيا', capital: 'سكوبي', currency: 'الدينار', continent: 'أوروبا' },
  { code: 'th', name: 'تايلاند', capital: 'بانكوك', currency: 'البات', continent: 'آسيا' },
  { code: 'vn', name: 'فيتنام', capital: 'هانوي', currency: 'الدونغ', continent: 'آسيا' },
  { code: 'ph', name: 'الفلبين', capital: 'مانيلا', currency: 'البيزو', continent: 'آسيا' },
  { code: 'kh', name: 'كمبوديا', capital: 'بنوم بنه', currency: 'الريال', continent: 'آسيا' },
  { code: 'mm', name: 'ميانمار', capital: 'نايبيداو', currency: 'الكيات', continent: 'آسيا' },
  { code: 'bd', name: 'بنغلاديش', capital: 'دكا', currency: 'التاكا', continent: 'آسيا' },
  { code: 'lk', name: 'سريلانكا', capital: 'كولومبو', currency: 'الروبية', continent: 'آسيا' },
  { code: 'af', name: 'أفغانستان', capital: 'كابل', currency: 'الأفغاني', continent: 'آسيا' },
  { code: 'uz', name: 'أوزبكستان', capital: 'طشقند', currency: 'السوم', continent: 'آسيا' },
  { code: 'kz', name: 'كازاخستان', capital: 'أستانا', currency: 'التينغ', continent: 'آسيا' },
  { code: 'ke', name: 'كينيا', capital: 'نيروبي', currency: 'الشلن', continent: 'أفريقيا' },
  { code: 'et', name: 'إثيوبيا', capital: 'أديس أبابا', currency: 'البير', continent: 'أفريقيا' },
  { code: 'tz', name: 'تنزانيا', capital: 'دودوما', currency: 'الشلن', continent: 'أفريقيا' },
  { code: 'ug', name: 'أوغندا', capital: 'كمبالا', currency: 'الشلن', continent: 'أفريقيا' },
  { code: 'gh', name: 'غانا', capital: 'أكرا', currency: 'السيدي', continent: 'أفريقيا' },
  { code: 'ci', name: 'ساحل العاج', capital: 'ياموسوكرو', currency: 'فرنك سيفا', continent: 'أفريقيا' },
  { code: 'sn', name: 'السنغال', capital: 'داكار', currency: 'فرنك سيفا', continent: 'أفريقيا' },
  { code: 'cm', name: 'الكاميرون', capital: 'ياوندي', currency: 'فرنك سيفا', continent: 'أفريقيا' },
  { code: 'ao', name: 'أنغولا', capital: 'لواندا', currency: 'الكوانزا', continent: 'أفريقيا' },
  { code: 'mz', name: 'موزمبيق', capital: 'مابوتو', currency: 'المتيكال', continent: 'أفريقيا' },
  { code: 'mg', name: 'مدغشقر', capital: 'أنتاناناريفو', currency: 'أرياري', continent: 'أفريقيا' },
  { code: 'zw', name: 'زيمبابوي', capital: 'هراري', currency: 'الدولار', continent: 'أفريقيا' },
  { code: 'cu', name: 'كوبا', capital: 'هافانا', currency: 'البيزو', continent: 'أمريكا الشمالية' },
  { code: 'jm', name: 'جامايكا', capital: 'كينغستون', currency: 'الدولار', continent: 'أمريكا الشمالية' },
  { code: 'ht', name: 'هايتي', capital: 'بورت أو برانس', currency: 'الغورد', continent: 'أمريكا الشمالية' },
  { code: 'do', name: 'الدومينيكان', capital: 'سانتو دومينغو', currency: 'البيزو', continent: 'أمريكا الشمالية' },
  { code: 'is', name: 'آيسلندا', capital: 'ريكيافيك', currency: 'الكرونة', continent: 'أوروبا' },
  { code: 'cy', name: 'قبرص', capital: 'نيقوسيا', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'mt', name: 'مالطا', capital: 'فاليتا', currency: 'اليورو', continent: 'أوروبا' },
  { code: 'np', name: 'نيبال', capital: 'كاتماندو', currency: 'الروبية', continent: 'آسيا' },
  { code: 'bt', name: 'بوتان', capital: 'تيمفو', currency: 'النغولترم', continent: 'آسيا' },
  { code: 'mv', name: 'المالديف', capital: 'ماليه', currency: 'الروفيا', continent: 'آسيا' }
];

export const PLAYERS_DATA = [
  { id: 158023, name: 'ليونيل ميسي', country: 'الأرجنتين', club: 'إنتر ميامي' },
  { id: 20801, name: 'كريستيانو رونالدو', country: 'البرتغال', club: 'النصر' },
  { id: 190871, name: 'نيمار', country: 'البرازيل', club: 'الهلال' },
  { id: 231747, name: 'كيليان مبابي', country: 'فرنسا', club: 'ريال مدريد' },
  { id: 239085, name: 'إيرلينغ هالاند', country: 'النرويج', club: 'مانشستر سيتي' },
  { id: 192985, name: 'كيفين دي بروين', country: 'بلجيكا', club: 'مانشستر سيتي' },
  { id: 209331, name: 'محمد صلاح', country: 'مصر', club: 'ليفربول' },
  { id: 202126, name: 'هاري كين', country: 'إنجلترا', club: 'بايرن ميونخ' },
  { id: 188545, name: 'روبرت ليفاندوفسكي', country: 'بولندا', club: 'برشلونة' },
  { id: 165153, name: 'كريم بنزيما', country: 'فرنسا', club: 'الاتحاد' },
  { id: 208722, name: 'ساديو ماني', country: 'السنغال', club: 'النصر' },
  { id: 212831, name: 'أليسون بيكر', country: 'البرازيل', club: 'ليفربول' },
  { id: 192448, name: 'تير شتيغن', country: 'ألمانيا', club: 'برشلونة' },
  { id: 215914, name: 'نغولو كانتي', country: 'فرنسا', club: 'الاتحاد' },
  { id: 183277, name: 'إيدين هازارد', country: 'بلجيكا', club: 'معتزل' },
  { id: 176580, name: 'لويس سواريز', country: 'أوروغواي', club: 'إنتر ميامي' },
  { id: 177003, name: 'لوكا مودريتش', country: 'كرواتيا', club: 'ريال مدريد' },
  { id: 182521, name: 'توني كروس', country: 'ألمانيا', club: 'معتزل' },
  { id: 155862, name: 'سيرجيو راموس', country: 'إسبانيا', club: 'إشبيلية' },
  { id: 167495, name: 'مانويل نوير', country: 'ألمانيا', club: 'بايرن ميونخ' },
  { id: 238794, name: 'فينيسيوس جونيور', country: 'البرازيل', club: 'ريال مدريد' },
  { id: 252371, name: 'جود بيلينغهام', country: 'إنجلترا', club: 'ريال مدريد' },
  { id: 235212, name: 'أشرف حكيمي', country: 'المغرب', club: 'باريس سان جيرمان' },
  { id: 226161, name: 'رياض محرز', country: 'الجزائر', club: 'الأهلي' },
  { id: 200145, name: 'كاسيميرو', country: 'البرازيل', club: 'مانشستر يونايتد' },
  { id: 212622, name: 'جوشوا كيميتش', country: 'ألمانيا', club: 'بايرن ميونخ' },
  { id: 231443, name: 'عثمان ديمبيلي', country: 'فرنسا', club: 'باريس سان جيرمان' },
  { id: 194765, name: 'أنطوان غريزمان', country: 'فرنسا', club: 'أتلتيكو مدريد' },
  { id: 212198, name: 'برونو فيرنانديز', country: 'البرتغال', club: 'مانشستر يونايتد' },
  { id: 200389, name: 'يان أوبلاك', country: 'سلوفينيا', club: 'أتلتيكو مدريد' },
  { id: 168542, name: 'ديفيد سيلفا', country: 'إسبانيا', club: 'معتزل' },
  { id: 190460, name: 'كريستيان إريكسن', country: 'الدنمارك', club: 'مانشستر يونايتد' },
  { id: 201535, name: 'رافاييل فاران', country: 'فرنسا', club: 'كومو' },
  { id: 192505, name: 'روميلو لوكاكو', country: 'بلجيكا', club: 'نابولي' },
  { id: 239053, name: 'فيديريكو فالفيردي', country: 'أوروغواي', club: 'ريال مدريد' },
  { id: 235161, name: 'برناردو سيلفا', country: 'البرتغال', club: 'مانشستر سيتي' },
  { id: 239818, name: 'روبن دياز', country: 'البرتغال', club: 'مانشستر سيتي' },
  { id: 230621, name: 'جيانلويجي دوناروما', country: 'إيطاليا', club: 'باريس سان جيرمان' },
  { id: 199987, name: 'ياسين بونو', country: 'المغرب', club: 'الهلال' },
  { id: 216267, name: 'أندي روبرتسون', country: 'اسكتلندا', club: 'ليفربول' },
  { id: 231281, name: 'ترنت ألكساندر أرنولد', country: 'إنجلترا', club: 'ليفربول' },
  { id: 203376, name: 'فيرجيل فان دايك', country: 'هولندا', club: 'ليفربول' },
  { id: 231677, name: 'ماركوس راشفورد', country: 'إنجلترا', club: 'مانشستر يونايتد' },
  { id: 213345, name: 'كينغسلي كومان', country: 'فرنسا', club: 'بايرن ميونخ' },
  { id: 208333, name: 'إيمري تشان', country: 'ألمانيا', club: 'بوروسيا دورتموند' }
];

export const LOGOS_DATA = [
  { domain: 'apple.com', name: 'أبل' },
  { domain: 'google.com', name: 'جوجل' },
  { domain: 'microsoft.com', name: 'مايكروسوفت' },
  { domain: 'amazon.com', name: 'أمازون' },
  { domain: 'tesla.com', name: 'تيسلا' },
  { domain: 'spotify.com', name: 'سبوتيفاي' },
  { domain: 'netflix.com', name: 'نتفليكس' },
  { domain: 'cocacola.com', name: 'كوكاكولا' },
  { domain: 'bmw.com', name: 'بي أم دبليو' },
  { domain: 'toyota.com', name: 'تويوتا' },
  { domain: 'nike.com', name: 'نايكي' },
  { domain: 'adidas.com', name: 'أديداس' },
  { domain: 'pepsi.com', name: 'بيبسي' },
  { domain: 'facebook.com', name: 'فيسبوك' },
  { domain: 'x.com', name: 'إكس (تويتر)' },
  { domain: 'instagram.com', name: 'إنستغرام' },
  { domain: 'tiktok.com', name: 'تيك توك' },
  { domain: 'samsung.com', name: 'سامسونج' },
  { domain: 'sony.com', name: 'سوني' },
  { domain: 'mcdonalds.com', name: 'ماكدونالدز' },
  { domain: 'starbucks.com', name: 'ستاربكس' },
  { domain: 'ikea.com', name: 'ايكيا' },
  { domain: 'uber.com', name: 'أوبر' },
  { domain: 'airbnb.com', name: 'إير بي إن بي' },
  { domain: 'visa.com', name: 'فيزا' },
  { domain: 'mastercard.com', name: 'ماستركارد' },
  { domain: 'paypal.com', name: 'باي بال' },
  { domain: 'almarai.com', name: 'المراعي' },
  { domain: 'stc.com.sa', name: 'STC' },
  { domain: 'emirates.com', name: 'طيران الإمارات' }
];

export const MOVIE_IMAGES = [
  { name: 'تايتانيك', url: 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png' },
  { name: 'أفاتار', url: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Avatar-Teaser-Poster.jpg' },
  { name: 'الجوكر', url: 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg' },
  { name: 'باتمان (فرسان الظلام)', url: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg' },
  { name: 'استهلال (Inception)', url: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg' },
  { name: 'الأسد الملك', url: 'https://upload.wikimedia.org/wikipedia/en/3/3d/The_Lion_King_poster.jpg' },
  { name: 'هاري بوتر وحجر الفيلسوف', url: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Harry_Potter_and_the_Philosopher%27s_Stone_banner.png' },
  { name: 'سيد الخواتم: عودة الملك', url: 'https://upload.wikimedia.org/wikipedia/en/b/be/The_Lord_of_the_Rings_-_The_Return_of_the_King_%282003%29.jpg' },
  { name: 'الماتريكس', url: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg' },
  { name: 'أفنجرز: نهاية اللعبة', url: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg' },
  { name: 'سبايدرمان: لا عودة إلى الديار', url: 'https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg' },
  { name: 'بين النجوم', url: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg' },
  { name: 'المصارع', url: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png' },
  { name: 'وحيد في المنزل', url: 'https://upload.wikimedia.org/wikipedia/en/7/76/Home_alone_poster.jpg' },
  { name: 'فروزن (Frozen)', url: 'https://upload.wikimedia.org/wikipedia/en/0/05/Frozen_%282013_film%29_poster.jpg' },
  { name: 'شريك', url: 'https://upload.wikimedia.org/wikipedia/en/3/39/Shrek.jpg' }
];

export const ANIME_IMAGES = [
  { name: 'ناروتو', url: 'https://upload.wikimedia.org/wikipedia/en/9/94/NarutoCoverTankobon1.jpg' },
  { name: 'ون بيس', url: 'https://upload.wikimedia.org/wikipedia/en/9/90/One_Piece%2C_Volume_61_Cover_%28Japanese%29.jpg' },
  { name: 'هجوم العمالقة', url: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Shingeki_no_Kyojin_manga_volume_1.jpg' },
  { name: 'ديث نوت', url: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_1.jpg' },
  { name: 'بليتش', url: 'https://upload.wikimedia.org/wikipedia/en/7/72/Bleach_manga_cover_1.jpg' },
  { name: 'دراغون بول', url: 'https://upload.wikimedia.org/wikipedia/en/c/c6/Dragon_Ball_Volume_1.jpg' },
  { name: 'هنتر x هنتر', url: 'https://upload.wikimedia.org/wikipedia/en/0/0f/Hunter_x_Hunter_cover_-_vol1.jpg' },
  { name: 'قاتل الشياطين', url: 'https://upload.wikimedia.org/wikipedia/en/0/09/Demon_Slayer_-_Kimetsu_no_Yaiba%2C_volume_1.jpg' },
  { name: 'جوجوتسو كايسن', url: 'https://upload.wikimedia.org/wikipedia/en/4/46/Jujutsu_kaisen.jpg' },
  { name: 'ون بانش مان', url: 'https://upload.wikimedia.org/wikipedia/en/c/c3/OnePunchMan_vol01.jpg' },
  { name: 'أكاديمية بطلي', url: 'https://upload.wikimedia.org/wikipedia/en/5/5a/Boku_no_Hero_Academia_Volume_1.png' },
  { name: 'اسمك (Your Name)', url: 'https://upload.wikimedia.org/wikipedia/en/0/0b/Your_Name_poster.png' },
  { name: 'مخطوفة (Spirited Away)', url: 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png' },
  { name: 'طوكيو غول', url: 'https://upload.wikimedia.org/wikipedia/en/e/e5/Tokyo_Ghoul_volume_1_cover.jpg' },
  { name: 'الخيميائي الفولاذي', url: 'https://upload.wikimedia.org/wikipedia/en/9/97/Fullmetal_Alchemist_vol_1.png' }
];
