export type LogoCategory = 'apps' | 'tech' | 'cars' | 'food' | 'games' | 'lifestyle' | 'finance' | 'travel';

export interface LogoItem {
  id: string;
  name: string;
  url: string;
  category: LogoCategory;
  difficulty: 1 | 2 | 3;
}

export const LOGOS_DATA: LogoItem[] = [
  { id: 'logo_4', name: "YouTube", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/youtube.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_9', name: "TikTok", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tiktok.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_7', name: "Instagram", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/instagram.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_1', name: "Facebook", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/facebook.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_8', name: "Snapchat", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/snapchat.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_5', name: "Discord", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/discord.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_2', name: "Telegram", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/telegram.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_3', name: "WhatsApp", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/whatsapp.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_10', name: "Spotify", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/spotify.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_6', name: "Netflix", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/netflix.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_11', name: "Pinterest", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/pinterest.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_18', name: "LinkedIn", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/linkedin.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_12', name: "Reddit", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/reddit.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_14', name: "Twitch", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/twitch.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_13', name: "Messenger", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/messenger.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_19', name: "Zoom", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/zoom.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_16', name: "Chrome", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/googlechrome.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_17', name: "Safari", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/safari.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_15', name: "Firefox", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/firefox.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_20', name: "Apple", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/apple.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_29', name: "Android", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/android.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_28', name: "Airbnb", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/airbnb.svg", category: 'apps' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_23', name: "Tinder", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tinder.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_21', name: "Waze", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/waze.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_22', name: "Vimeo", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/vimeo.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_30', name: "SoundCloud", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/soundcloud.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_25', name: "Slack", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/slack.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_24', name: "Notion", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/notion.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_27', name: "Asana", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/asana.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_26', name: "Trello", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/trello.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_40', name: "Figma", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/figma.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_38', name: "Dropbox", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/dropbox.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_36', name: "Evernote", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/evernote.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_32', name: "Strava", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/strava.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_31', name: "WeChat", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/wechat.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_34', name: "Line", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/line.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_33', name: "Signal", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/signal.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_35', name: "Viber", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/viber.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_37', name: "Duolingo", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/duolingo.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_39', name: "Kik", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/kik.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_46', name: "Tumblr", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tumblr.svg", category: 'apps' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_41', name: "Tripadvisor", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tripadvisor.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_42', name: "Yelp", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/yelp.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_43', name: "Shazam", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/shazam.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_48', name: "Coursera", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/coursera.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_45', name: "Udemy", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/udemy.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_44', name: "Bilibili", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bilibili.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_47', name: "Foursquare", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/foursquare.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_50', name: "KakaoTalk", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/kakaotalk.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_52', name: "React", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/react.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_54', name: "Vue.js", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/vuedotjs.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_55', name: "Angular", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/angular.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_53', name: "Git", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/git.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_49', name: "GitHub", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/github.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_56', name: "GitLab", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/gitlab.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_57', name: "Docker", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/docker.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_51', name: "Kubernetes", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/kubernetes.svg", category: 'apps' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_65', name: "macOS", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/macos.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_64', name: "Linux", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/linux.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_58', name: "Google", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/google.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_59', name: "Nvidia", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nvidia.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_61', name: "PlayStation", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/playstation.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_60', name: "Intel", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/intel.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_63', name: "AMD", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/amd.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_62', name: "Huawei", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/huawei.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_69', name: "Xiaomi", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/xiaomi.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_74', name: "Bluetooth", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bluetooth.svg", category: 'tech' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_66', name: "Ubuntu", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ubuntu.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_70', name: "Firebase", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/firebase.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_71', name: "Supabase", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/supabase.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_67', name: "MongoDB", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mongodb.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_73', name: "Redis", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/redis.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_72', name: "GraphQL", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/graphql.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_68', name: "Stripe", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/stripe.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_75', name: "Atlassian", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/atlassian.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_84', name: "Twilio", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/twilio.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_81', name: "Vercel", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/vercel.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_80', name: "Netlify", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/netlify.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_83', name: "Ethereum", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ethereum.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_82', name: "Bitcoin", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bitcoin.svg", category: 'tech' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_76', name: "Debian", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/debian.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_77', name: "CentOS", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/centos.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_78', name: "Raspberry Pi", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/raspberrypi.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_79', name: "Arduino", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/arduino.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_94', name: "Fedora", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/fedora.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_86', name: "Red Hat", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/redhat.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_85', name: "SUSE", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/suse.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_92', name: "Go", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/go.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_88', name: "Rust", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/rust.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_91', name: "Ruby", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ruby.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_90', name: "PHP", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/php.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_89', name: "Kotlin", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/kotlin.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_93', name: "Swift", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/swift.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_87', name: "Flutter", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/flutter.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_95', name: "Solana", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/solana.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_100', name: "Polkadot", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/polkadot.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_98', name: "Cardano", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/cardano.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_101', name: "Dogecoin", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/dogecoin.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_103', name: "Litecoin", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/litecoin.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_97', name: "Binance", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/binance.svg", category: 'tech' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_99', name: "BMW", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bmw.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_96', name: "Mercedes-Benz", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mercedes.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_102', name: "Audi", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/audi.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_113', name: "Toyota", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/toyota.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_109', name: "Honda", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/honda.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_111', name: "Ferrari", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ferrari.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_108', name: "Lamborghini", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/lamborghini.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_104', name: "Porsche", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/porsche.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_106', name: "Volkswagen", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/volkswagen.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_105', name: "Chevrolet", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/chevrolet.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_107', name: "Hyundai", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/hyundai.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_110', name: "Tesla", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tesla.svg", category: 'cars' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_112', name: "Mazda", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mazda.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_120', name: "Subaru", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/subaru.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_121', name: "Mitsubishi", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mitsubishi.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_115', name: "Peugeot", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/peugeot.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_116', name: "Volvo", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/volvo.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_114', name: "Renault", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/renault.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_118', name: "Aston Martin", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/astonmartin.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_122', name: "Bentley", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bentley.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_117', name: "Rolls-Royce", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/rollsroyce.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_119', name: "Maserati", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/maserati.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_124', name: "Bugatti", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bugatti.svg", category: 'cars' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_130', name: "McLaren", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mclaren.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_123', name: "Land Rover", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/landrover.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_126', name: "Jaguar", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/jaguar.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_125', name: "Mini", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mini.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_129', name: "Alfa Romeo", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/alfaromeo.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_127', name: "Skoda", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/skoda.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_128', name: "Seat", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/seat.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_131', name: "Dacia", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/dacia.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_133', name: "Acura", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/acura.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_135', name: "Chrysler", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/chrysler.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_132', name: "Mahindra", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mahindra.svg", category: 'cars' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_134', name: "McDonald's", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/mcdonalds.svg", category: 'food' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_137', name: "Starbucks", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/starbucks.svg", category: 'food' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_136', name: "Taco Bell", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/tacobell.svg", category: 'food' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_138', name: "KFC", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/kfc.svg", category: 'food' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_141', name: "Red Bull", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/redbull.svg", category: 'food' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_139', name: "Monster Energy", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/monster.svg", category: 'food' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_140', name: "Unilever", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/unilever.svg", category: 'food' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_142', name: "Steam", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/steam.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_145', name: "Epic Games", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/epicgames.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_143', name: "Riot Games", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/riotgames.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_144', name: "Rockstar Games", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/rockstargames.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_146', name: "Nintendo", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nintendo.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_151', name: "Ubisoft", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ubisoft.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_148', name: "Roblox", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/roblox.svg", category: 'games' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_147', name: "Valorant", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/valorant.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_149', name: "League of Legends", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/leagueoflegends.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_150', name: "Unity", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/unity.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_153', name: "Unreal Engine", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/unrealengine.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_152', name: "PUBG", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/pubg.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_156', name: "CD Projekt Red", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/cdprojekt.svg", category: 'games' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_154', name: "Bungie", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/bungie.svg", category: 'games' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_157', name: "Square Enix", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/squareenix.svg", category: 'games' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_158', name: "Konami", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/konami.svg", category: 'games' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_155', name: "Sega", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/sega.svg", category: 'games' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_159', name: "Valve", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/valve.svg", category: 'games' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_162', name: "Nike", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/nike.svg", category: 'lifestyle' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_161', name: "Adidas", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/adidas.svg", category: 'lifestyle' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_160', name: "Puma", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/puma.svg", category: 'lifestyle' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_163', name: "Under Armour", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/underarmour.svg", category: 'lifestyle' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_164', name: "New Balance", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/newbalance.svg", category: 'lifestyle' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_165', name: "Reebok", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/reebok.svg", category: 'lifestyle' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_166', name: "Uber", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/uber.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_168', name: "Lyft", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/lyft.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_167', name: "Airbnb", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/airbnb.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_169', name: "Delta", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/delta.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_172', name: "Emirates", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/emirates.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_170', name: "Qatar Airways", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/qatarairways.svg", category: 'travel' as LogoCategory, difficulty: 1 as 1|2|3 },
  { id: 'logo_171', name: "Lufthansa", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/lufthansa.svg", category: 'travel' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_173', name: "British Airways", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/britishairways.svg", category: 'travel' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_177', name: "Ryanair", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/ryanair.svg", category: 'travel' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_174', name: "EasyJet", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/easyjet.svg", category: 'travel' as LogoCategory, difficulty: 2 as 1|2|3 },
  { id: 'logo_178', name: "KLM", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/klm.svg", category: 'travel' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_176', name: "Singapore Airlines", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/singaporeairlines.svg", category: 'travel' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_179', name: "Qantas", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/qantas.svg", category: 'travel' as LogoCategory, difficulty: 3 as 1|2|3 },
  { id: 'logo_175', name: "Air Canada", url: "https://cdn.jsdelivr.net/npm/simple-icons@v13/icons/aircanada.svg", category: 'travel' as LogoCategory, difficulty: 3 as 1|2|3 },
];