import { ProverbData } from './types';
export const EGYPTIAN_PROVERBS_2: ProverbData[] = [
  { text: "اللي خدته القرعة تاخده أم", completions: { correct: "الشعور", wrong: ["العيون", "الخدود", "الرموش"] }, type: 'proverb', difficulty: 0 },
  { text: "يا قاعدين يكفيكوا شر", completions: { correct: "الجايين", wrong: ["الرايحين", "النايمين", "الماشين"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يعرفش يقول", completions: { correct: "عدس", wrong: ["طعمية", "فول", "حمص"] }, type: 'proverb', difficulty: 0 },
  { text: "طريق السلامة يا", completions: { correct: "متر", wrong: ["باشا", "بيه", "سيد"] }, type: 'proverb', difficulty: 0 },
  { text: "الغاوي ينقط بـ", completions: { correct: "طاقيته", wrong: ["فلوسه", "جلابيته", "قميصه"] }, type: 'proverb', difficulty: 1 },
  { text: "ياما جاب الغراب لأمه", completions: { correct: "تفاءل", wrong: ["خراب", "حجر", "ورد"] }, type: 'proverb', difficulty: 1 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["إيديك", "جسمك", "نفسك"] }, type: 'proverb', difficulty: 0 },
  { text: "القرش الأبيض ينفع في اليوم", completions: { correct: "الأسود", wrong: ["الحزين", "الطويل", "الأحمر"] }, type: 'proverb', difficulty: 0 },
  { text: "قالوا الجمل طلع النخلة.. قلنا آدي الجمل وآدي", completions: { correct: "النخلة", wrong: ["السما", "الأرض", "الشجرة"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي بيته من إزاز ما يحدفش الناس بالـ", completions: { correct: "طوب", wrong: ["حجارة", "نار", "مايه"] }, type: 'proverb', difficulty: 0 },
  { text: "قال يا محلى الكحل في العين", completions: { correct: "الواسعة", wrong: ["الضيقة", "الحلوة", "الجميلة"] }, type: 'proverb', difficulty: 2 },
  { text: "حبيبك يبلعلك الزلط وعدوك يتمنالك", completions: { correct: "الغلط", wrong: ["المرض", "الموت", "الوقوع"] }, type: 'proverb', difficulty: 0 },
  { text: "بعد ما شاب ودوه", completions: { correct: "الكُتّاب", wrong: ["المدرسة", "الجامعة", "البيت"] }, type: 'proverb', difficulty: 0 },
  { text: "ديل الكلب عمره ما يتعدل ولو علقوله", completions: { correct: "قالب", wrong: ["ذهب", "حبل", "حجر"] }, type: 'proverb', difficulty: 1 },
  { text: "بات مغلوب ولا تبات", completions: { correct: "غالب", wrong: ["ظالم", "حرامي", "كذاب"] }, type: 'proverb', difficulty: 1 },
  { text: "الحي أبقى من", completions: { correct: "الميت", wrong: ["النايم", "الغايب", "المريض"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يتلسع من الشوربة ينفخ في", completions: { correct: "الزبادي", wrong: ["اللبن", "العصير", "المية"] }, type: 'proverb', difficulty: 0 },
  { text: "امسك الخشب حسن لا", completions: { correct: "تتحسد", wrong: ["تزعل", "تطيح", "تموت"] }, type: 'proverb', difficulty: 0 },
  { text: "يا خبر النهاردة بفلوس بكرة يبقى بـ", completions: { correct: "بلاش", wrong: ["ذهب", "تراب", "رخيص"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي في القلب في", completions: { correct: "القلب", wrong: ["العقل", "الروح", "العين"] }, type: 'proverb', difficulty: 0 },
  { text: "ادعي على ابني واكره اللي يقول", completions: { correct: "آمين", wrong: ["يا رب", "صحيح", "كلامك"] }, type: 'proverb', difficulty: 1 },
  { text: "المتعوس متعوس ولو علقوا على بابه", completions: { correct: "فانوس", wrong: ["ذهب", "نور", "ورد"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي مكتوب على الجبين لازم تشوفه", completions: { correct: "العين", wrong: ["الناس", "الدنيا", "الروح"] }, type: 'proverb', difficulty: 0 },
  { text: "جت الحزينة تفرح ما لقتلهاش", completions: { correct: "مطرح", wrong: ["مكان", "كرسي", "صاحب"] }, type: 'proverb', difficulty: 0 },
  { text: "خيراً تعمل شراً", completions: { correct: "تلقى", wrong: ["تحصد", "تجد", "تأخذ"] }, type: 'wisdom', difficulty: 0 },
  { text: "يا بخت من وفق راسين في", completions: { correct: "الحلال", wrong: ["الحب", "الخير", "الجواز"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ايده في المية مش زي اللي ايده في", completions: { correct: "النار", wrong: ["التراب", "الهوا", "الدم"] }, type: 'proverb', difficulty: 0 },
  { text: "ما يقع إلا", completions: { correct: "الشاطر", wrong: ["الغبي", "الخايب", "الجاهل"] }, type: 'proverb', difficulty: 0 },
  { text: "كل فولة ولها", completions: { correct: "كيال", wrong: ["بياع", "شراي", "صاحب"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي يربط في رقبته حبل، ألف مين", completions: { correct: "يسحبه", wrong: ["يخنقه", "يقطعه", "يعلقه"] }, type: 'proverb', difficulty: 1 },
  { text: "طبخ السم", completions: { correct: "بيدوقه", wrong: ["بياكله", "بيشربه", "بيموت بيه"] }, type: 'proverb', difficulty: 0 },
  { text: "لا تذم ولا تشكر إلا بعد", completions: { correct: "ست أشهر", wrong: ["سنة", "يومين", "شهرين"] }, type: 'wisdom', difficulty: 2 },
  { text: "اللي يخاف من العفريت", completions: { correct: "يطلعلوا", wrong: ["ياكله", "ينام", "يهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "باب النجار", completions: { correct: "مخلع", wrong: ["مكسور", "حديد", "خشب"] }, type: 'proverb', difficulty: 0 },
  { text: "من خرج من داره اتقل", completions: { correct: "مقداره", wrong: ["احترامه", "ميزانه", "ماله"] }, type: 'proverb', difficulty: 0 },
  { text: "ابنك على ما تربيه، وجوزك على ما", completions: { correct: "تعوديه", wrong: ["تحبيه", "تكبريه", "تهاديه"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور في الايد احسن من عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الارض", "السما"] }, type: 'proverb', difficulty: 0 },
  { text: "اخطب لبنتك ولا تخطب", completions: { correct: "لابنك", wrong: ["لاخوك", "لنفسك", "لابوك"] }, type: 'wisdom', difficulty: 1 },
  { text: "الضرب في الميت", completions: { correct: "حرام", wrong: ["مكروه", "تعب", "وجع"] }, type: 'proverb', difficulty: 0 },
  { text: "يدي الحلق للي بلا", completions: { correct: "ودان", wrong: ["رقبة", "فلوس", "عقل"] }, type: 'proverb', difficulty: 0 },
  { text: "دخول الحمام مش زي", completions: { correct: "خروجه", wrong: ["قعاده", "نظافته", "بابه"] }, type: 'proverb', difficulty: 0 },
  { text: "ضربني وبكى سبقني", completions: { correct: "واشتكى", wrong: ["وجرى", "وقال", "وراح"] }, type: 'proverb', difficulty: 0 },
  { text: "في الوش مراية وفي القفا", completions: { correct: "سلاية", wrong: ["سكينة", "شوكه", "حجارة"] }, type: 'proverb', difficulty: 1 },
  { text: "لبس البوصة تبقى", completions: { correct: "عروسة", wrong: ["وردة", "حلوة", "زينة"] }, type: 'proverb', difficulty: 0 },
  { text: "امشي في جنازة ولا تمشي في", completions: { correct: "جوازة", wrong: ["طريق", "مصيبة", "حفلة"] }, type: 'proverb', difficulty: 1 },
  { text: "القرد في عين أمه", completions: { correct: "غزال", wrong: ["أسد", "قمر", "نمر"] }, type: 'proverb', difficulty: 0 },
  { text: "يخلق من الشبه", completions: { correct: "أربعين", wrong: ["سبعين", "عشرين", "مية"] }, type: 'proverb', difficulty: 0 },
  { text: "داري على شمعتك", completions: { correct: "تقيد", wrong: ["تنور", "تنطفي", "تولع"] }, type: 'proverb', difficulty: 0 },
  { text: "زي القطط بسبع", completions: { correct: "ارواح", wrong: ["عيون", "سنون", "ايادي"] }, type: 'proverb', difficulty: 0 },
  { text: "الغايب حجته", completions: { correct: "معاه", wrong: ["عذره", "بكرة", "وراه"] }, type: 'proverb', difficulty: 0 }
];
