import { ProverbData } from './types';
export const EGYPTIAN_PROVERBS: ProverbData[] = [
  { text: "اللي بيته من إزاز ما يحدفش الناس بالـ", completions: { correct: "طوب", wrong: ["حجارة", "نار", "كلام"] }, type: 'proverb', difficulty: 0 },
  { text: "ابن الوز", completions: { correct: "عوام", wrong: ["طواش", "طخاخ", "بياع"] }, type: 'proverb', difficulty: 0 },
  { text: "القرعة تتباهى بشعر بنت", completions: { correct: "أختها", wrong: ["خالتها", "عمتها", "جارتها"] }, type: 'proverb', difficulty: 1 },
  { text: "اقلب القدرة على فمها تطلع البت لـ", completions: { correct: "أمها", wrong: ["جدتها", "شبهها", "أبوها"] }, type: 'proverb', difficulty: 0 },
  { text: "امشي في جنازة ولا تمشي في", completions: { correct: "جوازة", wrong: ["فرح", "سوق", "خصومة"] }, type: 'proverb', difficulty: 1 },
  { text: "علمناهم الشحاتة سبقونا على", completions: { correct: "الأبواب", wrong: ["الرزق", "الصف", "الحواري"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي يتلسع من الشوربة ينفخ في الـ", completions: { correct: "زبادي", wrong: ["ميه", "لبن", "هوا"] }, type: 'proverb', difficulty: 0 },
  { text: "دخول الحمام مش زي", completions: { correct: "خروجه", wrong: ["قعاده", "بابه", "زمانه"] }, type: 'proverb', difficulty: 0 },
  { text: "ضربني وبكى وسبقني و", completions: { correct: "اشتكى", wrong: ["جرى", "ختم", "حكى"] }, type: 'proverb', difficulty: 0 },
  { text: "يخلق من الشبه", completions: { correct: "أربعين", wrong: ["خمسين", "مية", "عشرة"] }, type: 'proverb', difficulty: 0 },
  { text: "مراية الحب", completions: { correct: "عميا", wrong: ["كاذبة", "مكسورة", "بتلمع"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي ما يشوفش من الغربال يبقى", completions: { correct: "أعمى", wrong: ["أطرش", "نايم", "غبي"] }, type: 'proverb', difficulty: 1 },
  { text: "يا خبر بفلوس بكرة يبقى بـ", completions: { correct: "بلاش", wrong: ["أغلى", "تراب", "ذهب"] }, type: 'proverb', difficulty: 0 },
  { text: "عشمتني بالحلق خرمت أنا", completions: { correct: "وداني", wrong: ["مناخيري", "إيدي", "ثوبي"] }, type: 'proverb', difficulty: 1 },
  { text: "القرد في عين أمه", completions: { correct: "غزال", wrong: ["نمر", "أمير", "أسد"] }, type: 'proverb', difficulty: 0 },
  { text: "الحلو حلو لو قام من", completions: { correct: "النوم", wrong: ["المقابر", "الأكل", "الحمام"] }, type: 'proverb', difficulty: 1 },
  { text: "الوحش وحش لو غسل وشه كل", completions: { correct: "يوم", wrong: ["ساعة", "شوية", "لحظة"] }, type: 'proverb', difficulty: 1 },
  { text: "كدب الإبل ولا كدب الـ", completions: { correct: "رجالة", wrong: ["نسوان", "أطفال", "تجار"] }, type: 'proverb', difficulty: 2 },
  { text: "لو كان للموت رشوة كنت رشيت", completions: { correct: "عزرائيل", wrong: ["الحفار", "الملك", "الوزير"] }, type: 'proverb', difficulty: 2 },
  { text: "لبس البوصة تبقى", completions: { correct: "عروسة", wrong: ["جميلة", "وردة", "ملكة"] }, type: 'proverb', difficulty: 0 },
  { text: "في الوش مراية وفي القفا", completions: { correct: "سلاية", wrong: ["سكينة", "مقشة", "حجارة"] }, type: 'proverb', difficulty: 2 },
  { text: "الغايب حجته", completions: { correct: "معاه", wrong: ["عذره", "بكرة", "في بيته"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ملوش كبير يشتريله", completions: { correct: "كبير", wrong: ["كلب", "عكاز", "محامي"] }, type: 'proverb', difficulty: 0 },
  { text: "الدار دار أبونا والقوم", completions: { correct: "طردونا", wrong: ["حبونا", "عادونا", "ضربونا"] }, type: 'proverb', difficulty: 1 },
  { text: "زي القطط بسبع", completions: { correct: "أرواح", wrong: ["عيون", "أسنان", "رجول"] }, type: 'proverb', difficulty: 0 },
  { text: "يا واخد القرد على ماله يروح المال ويفضل القرد على", completions: { correct: "حاله", wrong: ["شجالته", "غبائه", "جماله"] }, type: 'proverb', difficulty: 1 },
  { text: "قالوا للحرامي احلف قال جاني الـ", completions: { correct: "فرج", wrong: ["رزق", "عفو", "عذاب"] }, type: 'proverb', difficulty: 1 },
  { text: "حبيبك يبلع لك الزلط، وعدوك يتمنى لك الـ", completions: { correct: "غلط", wrong: ["فشل", "مرض", "موت"] }, type: 'proverb', difficulty: 0 },
  { text: "اتغدى بيه قبل ما يتعشى", completions: { correct: "بيك", wrong: ["بأهلك", "بالناس", "بره"] }, type: 'proverb', difficulty: 0 },
  { text: "جت الحزينة تفرح مالقتلهاش", completions: { correct: "مطرح", wrong: ["مكان", "كرسي", "فرح"] }, type: 'proverb', difficulty: 0 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["إيديك", "راسك", "جسمك"] }, type: 'proverb', difficulty: 0 },
  { text: "داري على شمعتك", completions: { correct: "تقيد", wrong: ["تنطفي", "تولع", "تكبر"] }, type: 'proverb', difficulty: 0 },
  { text: "القرش الأبيض ينفع في اليوم", completions: { correct: "الأسود", wrong: ["الأحمر", "الصعب", "القاسي"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور في الإيد ولا عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "الحيط"] }, type: 'proverb', difficulty: 0 },
  { text: "يدي الحلق للي بلا", completions: { correct: "ودان", wrong: ["رقبة", "فلوس", "شعر"] }, type: 'proverb', difficulty: 1 }
];
