import { ProverbData } from './types';
export const FUSHA_PROVERBS_2: ProverbData[] = [
  { text: "رب أخ لك لم تلده", completions: { correct: "أمك", wrong: ["زوجتك", "ابنتك", "أختك"] }, type: 'wisdom', difficulty: 0 },
  { text: "الساكت عن الحق شيطان", completions: { correct: "أخرس", wrong: ["ناطق", "أصم", "أعمى"] }, type: 'wisdom', difficulty: 0 },
  { text: "شر البلية ما", completions: { correct: "يضحك", wrong: ["يبكي", "يحزن", "يؤلم"] }, type: 'wisdom', difficulty: 0 },
  { text: "عاد بخفي", completions: { correct: "حنين", wrong: ["ذئب", "نادم", "ثعلب"] }, type: 'saying', difficulty: 0 },
  { text: "عاند الدنيا و", completions: { correct: "ابتسم", wrong: ["احزن", "اغضب", "ابك"] }, type: 'wisdom', difficulty: 1 },
  { text: "عذر أقبح من", completions: { correct: "ذنب", wrong: ["خطيئة", "فعل", "زلّة"] }, type: 'wisdom', difficulty: 0 },
  { text: "في العجلة الندامة وفي التأني", completions: { correct: "السلامة", wrong: ["الخسارة", "الفوز", "الراحة"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل إناء بما فيه", completions: { correct: "ينضح", wrong: ["يفيض", "يقطر", "يمتلئ"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل فتاة بأبيها", completions: { correct: "معجبة", wrong: ["مغرمة", "مشغوفة", "مبهورة"] }, type: 'wisdom', difficulty: 0 },
  { text: "لا تؤجل عمل اليوم إلى", completions: { correct: "الغد", wrong: ["الليل", "المساء", "الصباح"] }, type: 'wisdom', difficulty: 0 },
  { text: "لا يلدغ المؤمن من جحر", completions: { correct: "مرتين", wrong: ["ثلاث", "مرة", "أبدا"] }, type: 'wisdom', difficulty: 0 },
  { text: "الطيور على أشكالها", completions: { correct: "تقع", wrong: ["تطير", "تتلاقى", "تأكل"] }, type: 'wisdom', difficulty: 0 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["عليها", "تحتها", "بها"] }, type: 'wisdom', difficulty: 0 },
  { text: "من شب على شيء شاب", completions: { correct: "عليه", wrong: ["إليه", "فيه", "له"] }, type: 'wisdom', difficulty: 0 },
  { text: "إذا لم تستح فاصنع ما", completions: { correct: "شئت", wrong: ["أردت", "حللت", "نويت"] }, type: 'wisdom', difficulty: 0 },
  { text: "أول الغيث قطرة ثم", completions: { correct: "ينهمر", wrong: ["يمطر", "يكثر", "يغزر"] }, type: 'wisdom', difficulty: 0 },
  { text: "السيف أصدق أنباء من", completions: { correct: "الكتب", wrong: ["الأقلام", "الكلام", "الصحف"] }, type: 'wisdom', difficulty: 1 },
  { text: "إذا أنت أكرمت الكريم ملكته وإن أنت أكرمت اللئيم", completions: { correct: "تمردا", wrong: ["تكبرا", "تنكرا", "تجبرا"] }, type: 'wisdom', difficulty: 1 },
  { text: "إذا الشعب يوما أراد الحياة فلا بد أن يستجيب", completions: { correct: "القدر", wrong: ["العالم", "الله", "الزمن"] }, type: 'wisdom', difficulty: 0 },
  { text: "الأم مدرسة إذا أعددتها أعددت شعبا طيب", completions: { correct: "الأعراق", wrong: ["الأصل", "الأخلاق", "النبات"] }, type: 'wisdom', difficulty: 0 },
  { text: "ألا ليت الشباب يعود", completions: { correct: "يوما", wrong: ["دهرا", "شهرا", "ساعة"] }, type: 'wisdom', difficulty: 0 },
  { text: "إنما الأمم الأخلاق ما بقيت فإن هم ذهبت أخلاقهم", completions: { correct: "ذهبوا", wrong: ["ماتوا", "زالوا", "سقطوا"] }, type: 'wisdom', difficulty: 1 },
  { text: "وما نيل المطالب بالتمني ولكن تؤخذ الدنيا", completions: { correct: "غلابا", wrong: ["كفاحا", "عنادا", "سهاما"] }, type: 'wisdom', difficulty: 1 },
  { text: "لا تحسبن المجد تمرا أنت آكله لن تبلغ المجد حتى تلعق", completions: { correct: "الصبرا", wrong: ["العسلا", "السما", "الأرضا"] }, type: 'wisdom', difficulty: 1 },
  { text: "رأيي صواب يحتمل الخطأ ورأي غيري خطأ يحتمل", completions: { correct: "الصواب", wrong: ["اليقين", "الصدق", "الشك"] }, type: 'wisdom', difficulty: 1 },
  { text: "لكل داء دواء يستطب به إلا الحماقة أعيت من", completions: { correct: "يداويها", wrong: ["يفهمها", "يعالجها", "يشفيها"] }, type: 'wisdom', difficulty: 1 },
  { text: "نعيب زماننا والعيب فينا وما لزماننا عيب", completions: { correct: "سوانا", wrong: ["إلانا", "معنا", "غيرنا"] }, type: 'wisdom', difficulty: 1 }
];
