import { ProverbData } from './types';
export const GULF_PROVERBS_2: ProverbData[] = [
  { text: "اللي ما يعرف الصقر", completions: { correct: "يشويه", wrong: ["يصيده", "يربيه", "يفكه"] }, type: 'proverb', difficulty: 0 },
  { text: "عنزة الفريج ما تحب الا الـ", completions: { correct: "تيس الغريب", wrong: ["جمر", "نخل", "ربيع"] }, type: 'proverb', difficulty: 2 },
  { text: "امك صناجة وابوك", completions: { correct: "اعمى", wrong: ["اطرش", "ابكم", "مجنون"] }, type: 'proverb', difficulty: 1 },
  { text: "زين الخلايق في", completions: { correct: "أخلاقها", wrong: ["أفعالها", "أقوالها", "أشكالها"] }, type: 'proverb', difficulty: 1 },
  { text: "مال البخيل ياكله", completions: { correct: "العيار", wrong: ["الحرامي", "الذيب", "الغريب"] }, type: 'proverb', difficulty: 1 },
  { text: "ما يمدح السوق الا من", completions: { correct: "ربح فيه", wrong: ["باع فيه", "شرى فيه", "مشى فيه"] }, type: 'proverb', difficulty: 0 },
  { text: "من طول الغيبات جاب", completions: { correct: "الغايم", wrong: ["الهدايا", "الأخبار", "النهايم"] }, type: 'proverb', difficulty: 0 },
  { text: "مادح نفسه يبيله", completions: { correct: "رفسة", wrong: ["ضربة", "صفقة", "ضحكة"] }, type: 'proverb', difficulty: 1 },
  { text: "اذا طاح الجمل كثرت", completions: { correct: "سكاكينه", wrong: ["همومه", "مشاكله", "أحزانه"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي في الجدر يطلعه الـ", completions: { correct: "ملاس", wrong: ["صحن", "خياش", "وقت"] }, type: 'proverb', difficulty: 1 },
  { text: "طول الخيط وطير", completions: { correct: "البالون", wrong: ["العصفور", "الغراب", "الحمامة"] }, type: 'proverb', difficulty: 1 },
  { text: "سيل ما يبلك ما", completions: { correct: "يهمك", wrong: ["يغرقك", "يبلك", "يضرك"] }, type: 'proverb', difficulty: 1 },
  { text: "وين ما تطقها", completions: { correct: "عوية", wrong: ["عدلة", "مكسورة", "طايحة"] }, type: 'proverb', difficulty: 1 },
  { text: "لا تبوق ولا", completions: { correct: "تخاف", wrong: ["تهيم", "تعادي", "تحزن"] }, type: 'proverb', difficulty: 0 },
  { text: "حشر مع الناس", completions: { correct: "عيد", wrong: ["عذاب", "موت", "نعيم"] }, type: 'proverb', difficulty: 0 },
  { text: "الي ما يطول العنب حامضٍ عنه", completions: { correct: "يقول", wrong: ["يحكي", "يسكت", "يرمي"] }, type: 'proverb', difficulty: 0 },
  { text: "الباب اللي يجيك منه الريح سده و", completions: { correct: "استريح", wrong: ["اقفله", "نام", "ابعد"] }, type: 'proverb', difficulty: 0 },
  { text: "عط الخباز خبزه لو اكل", completions: { correct: "نصه", wrong: ["كله", "ربعه", "شويه"] }, type: 'proverb', difficulty: 0 },
  { text: "لو تجري جري الوحوش غير رزقك ما", completions: { correct: "تحوش", wrong: ["تاخذ", "تلقى", "تشوف"] }, type: 'proverb', difficulty: 0 },
  { text: "يا من شرا له من حلاله", completions: { correct: "علة", wrong: ["هم", "سيارة", "دابة"] }, type: 'proverb', difficulty: 1 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["عليها", "تحتها", "جنبها"] }, type: 'proverb', difficulty: 0 },
  { text: "الطول طول نخلة والعقل عقل", completions: { correct: "صخلة", wrong: ["طفل", "نعجة", "جاهل"] }, type: 'proverb', difficulty: 1 },
  { text: "قال انفخ يا شريم قال ما من", completions: { correct: "برطم", wrong: ["فم", "هواء", "قلب"] }, type: 'proverb', difficulty: 2 },
  { text: "ردت حليمة لعادتها", completions: { correct: "القديمة", wrong: ["السيئة", "المقيتة", "البالية"] }, type: 'proverb', difficulty: 0 },
  { text: "بغى يكحلها", completions: { correct: "عماها", wrong: ["بجاها", "وجعها", "اضرها"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يده في الماء مو مثل اللي يده في", completions: { correct: "النار", wrong: ["التراب", "الجليد", "الهواء"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يخاف من الله", completions: { correct: "خافه", wrong: ["احترمه", "اتركه", "ابعد عنه"] }, type: 'wisdom', difficulty: 1 },
  { text: "إذا صار رفيجك حلو لا تاكله", completions: { correct: "كله", wrong: ["نصه", "شوي", "قطعة"] }, type: 'proverb', difficulty: 0 },
  { text: "نوم الظالم", completions: { correct: "عبادة", wrong: ["راحة", "نعمة", "سعادة"] }, type: 'wisdom', difficulty: 1 },
  { text: "الطيور على أشكالها", completions: { correct: "تقع", wrong: ["تطير", "تنام", "تهاجر"] }, type: 'wisdom', difficulty: 0 }
];
