import { ProverbData } from './types';
export const IRAQI_PROVERBS_2: ProverbData[] = [
  { text: "ودع البزون شحمة", completions: { correct: "طيرها", wrong: ["ياكلها", "ينساها", "يعوفها"] }, type: 'proverb', difficulty: 2 },
  { text: "يا من تعب يا من شقى يا من على الحاضر", completions: { correct: "لكى", wrong: ["اجى", "بكى", "غفى"] }, type: 'proverb', difficulty: 1 },
  { text: "تجيك التهايم وانت", completions: { correct: "نايم", wrong: ["كاعد", "صايم", "قايم"] }, type: 'proverb', difficulty: 0 },
  { text: "الما يرضى بجزة يرضى بـ", completions: { correct: "خروف", wrong: ["عنزة", "صوف", "بقرة"] }, type: 'proverb', difficulty: 2 },
  { text: "عرب وين وطنبورة", completions: { correct: "وين", wrong: ["هناك", "بعيد", "ضايعة"] }, type: 'proverb', difficulty: 1 },
  { text: "يامن تعب يامن شقى يا من على الحاضر", completions: { correct: "لكى", wrong: ["اكل", "نام", "ضحك"] }, type: 'proverb', difficulty: 1 },
  { text: "اجه يكحلها", completions: { correct: "عماها", wrong: ["لعب بيها", "بجاها", "خربها"] }, type: 'proverb', difficulty: 0 },
  { text: "كل مشروك", completions: { correct: "مبروك", wrong: ["متروك", "مكروه", "مشبوه"] }, type: 'proverb', difficulty: 1 },
  { text: "بالوجه مراية وبالكفا", completions: { correct: "سلاية", wrong: ["حجاية", "حياية", "شوكه"] }, type: 'proverb', difficulty: 0 },
  { text: "ايد وحده ما", completions: { correct: "تصفك", wrong: ["تلزم", "تكتب", "تضرب"] }, type: 'proverb', difficulty: 0 },
  { text: "ما يعجبه العجب ولا الصيام في", completions: { correct: "رجب", wrong: ["شعبان", "رمضان", "الصيف"] }, type: 'proverb', difficulty: 1 },
  { text: "الجدر ما يكعد الا على", completions: { correct: "ثلاث", wrong: ["اثنين", "اربع", "وحده"] }, type: 'proverb', difficulty: 2 },
  { text: "لا تذم ولا تشكر الا بعد", completions: { correct: "ست اشهر", wrong: ["يومين", "ما تشوف", "ما تجرب"] }, type: 'proverb', difficulty: 2 },
  { text: "الخير مخير والشر", completions: { correct: "ميسر", wrong: ["مكرر", "مجرجر", "مقدر"] }, type: 'proverb', difficulty: 2 },
  { text: "لو تمطر تفاك همه لجلاب", completions: { correct: "تنباح", wrong: ["تخاف", "تنهزم", "تنعض"] }, type: 'proverb', difficulty: 2 },
  { text: "العين ما تعلى على", completions: { correct: "الحاجب", wrong: ["الراس", "الجفن", "الخشم"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يعرف يركص يكول الكاع", completions: { correct: "عوجه", wrong: ["حارة", "زلك", "تعبانة"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور باليد احسن من عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الحايط", "الواير"] }, type: 'proverb', difficulty: 0 },
  { text: "من شاف احبابه نسى", completions: { correct: "اصحابه", wrong: ["ربعه", "اهله", "عقله"] }, type: 'proverb', difficulty: 0 },
  { text: "بفلوسك حني", completions: { correct: "سكوسك", wrong: ["جفوفك", "راسك", "وجهك"] }, type: 'proverb', difficulty: 2 },
  { text: "عرس واوية، طك", completions: { correct: "بجواوية", wrong: ["هلاهل", "طبول", "اصوات"] }, type: 'proverb', difficulty: 2 },
  { text: "غرجان ومجلب بـ", completions: { correct: "كشاية", wrong: ["حبل", "بلم", "صخرة"] }, type: 'proverb', difficulty: 1 },
  { text: "تريد الحجي الموزين اسأل", completions: { correct: "الزعاطيط", wrong: ["النسوان", "الشياطين", "الجهال"] }, type: 'proverb', difficulty: 1 },
  { text: "الطول طول نخلة والعقل عقل", completions: { correct: "صخلة", wrong: ["نملة", "طلي", "دجاجة"] }, type: 'proverb', difficulty: 0 },
  { text: "الحرامي يكاد المرتاب ان يقول", completions: { correct: "خذوني", wrong: ["لزموني", "شوفوني", "قتلوني"] }, type: 'wisdom', difficulty: 1 },
  { text: "ياكل وينكر مثل الـ", completions: { correct: "بزون", wrong: ["جلب", "ذيب", "واوي"] }, type: 'proverb', difficulty: 1 },
  { text: "انطو للشايب مرة ونسه", completions: { correct: "المكبرة", wrong: ["عصاته", "بيته", "اولاده"] }, type: 'proverb', difficulty: 2 },
  { text: "صام صام وفطر على", completions: { correct: "بصلة", wrong: ["تمرة", "ماي", "تفاحة"] }, type: 'proverb', difficulty: 0 },
  { text: "الباب التجيك منه الريح سده و", completions: { correct: "استريح", wrong: ["ارتاح", "اسكت", "نام"] }, type: 'proverb', difficulty: 0 },
  { text: "يمد لحافه على كد", completions: { correct: "رجليه", wrong: ["فلوسه", "حاله", "طوله"] }, type: 'proverb', difficulty: 0 }
];
