import { ProverbData } from './types';
export const IRAQI_PROVERBS: ProverbData[] = [
  { text: "الما يلوح العنب يكول", completions: { correct: "حامض", wrong: ["أخضر", "حلو", "يابس"] }, type: 'proverb', difficulty: 0 },
  { text: "الطول طول نخلة، والعقل عقل", completions: { correct: "صخلة", wrong: ["نملة", "طفل", "ذباب"] }, type: 'proverb', difficulty: 1 },
  { text: "مبلل يخاف من", completions: { correct: "المطر", wrong: ["البرد", "البحر", "النهر"] }, type: 'proverb', difficulty: 1 },
  { text: "نايم ورجليك بالـ", completions: { correct: "شمس", wrong: ["ماء", "هواء", "طين"] }, type: 'proverb', difficulty: 1 },
  { text: "مثل البزون، ياكل عشاه و", completions: { correct: "يعيط", wrong: ["ينام", "يشرد", "يلعب"] }, type: 'proverb', difficulty: 2 },
  { text: "اللي ما يعرف يركص يكول الكاع", completions: { correct: "عوجه", wrong: ["زلقة", "حارة", "صغيرة"] }, type: 'proverb', difficulty: 1 },
  { text: "كلمن يحود النار لـ", completions: { correct: "كرصته", wrong: ["بيته", "أهله", "نفسه"] }, type: 'proverb', difficulty: 2 },
  { text: "ياكل ويشرب ويا الذيب، ويبچي ويا", completions: { correct: "الراعي", wrong: ["الغنم", "الكلب", "الأسد"] }, type: 'proverb', difficulty: 1 },
  { text: "مثل السمك، مأكول", completions: { correct: "مذموم", wrong: ["ممدوح", "مسلوق", "متروك"] }, type: 'proverb', difficulty: 1 },
  { text: "الكرعة تتباها بشعر بنت", completions: { correct: "أختها", wrong: ["خالتها", "عمتها", "جارتها"] }, type: 'proverb', difficulty: 1 },
  { text: "إجه يكحلها", completions: { correct: "عماها", wrong: ["بجاها", "لطمها", "ضربها"] }, type: 'proverb', difficulty: 0 },
  { text: "ايد وحده ما", completions: { correct: "تصفك", wrong: ["تضرب", "تبني", "تشتغل"] }, type: 'proverb', difficulty: 0 },
  { text: "تمسكن لحد ما", completions: { correct: "تمكن", wrong: ["تأمن", "تغنى", "تسلط"] }, type: 'proverb', difficulty: 1 },
  { text: "الباب التجيك منه الريح، سده و", completions: { correct: "استريح", wrong: ["نام", "ارتاح", "اسكت"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يلدغه الحية، يخاف من جرة", completions: { correct: "الحبل", wrong: ["العصا", "الخيط", "الشجرة"] }, type: 'proverb', difficulty: 0 },
  { text: "نقول ثور يقول", completions: { correct: "احلبوه", wrong: ["اربطوه", "اذبحوه", "بيعوه"] }, type: 'proverb', difficulty: 0 },
  { text: "حاميها", completions: { correct: "حراميها", wrong: ["راعيها", "بايعها", "تاركها"] }, type: 'proverb', difficulty: 0 },
  { text: "شين تعرفه أحسن من زين", completions: { correct: "تتعرف عليه", wrong: ["تجهله", "تسمع بيه", "ما تشوفه"] }, type: 'proverb', difficulty: 1 },
  { text: "صام صام وفطر على", completions: { correct: "بصلة", wrong: ["ثومة", "تمرة", "خبزة"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور باليد أحسن من عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الحايط", "السما"] }, type: 'proverb', difficulty: 0 },
  { text: "يركض والعشا", completions: { correct: "خباز", wrong: ["بصل", "تمن", "بلاش"] }, type: 'proverb', difficulty: 2 },
  { text: "مثل الاطرش بالـ", completions: { correct: "زفة", wrong: ["طرمة", "سوك", "صيحة"] }, type: 'proverb', difficulty: 1 },
  { text: "عمر الجلب ما ينعدل", completions: { correct: "ذيله", wrong: ["راسه", "طبعه", "حاله"] }, type: 'proverb', difficulty: 1 },
  { text: "اني واخوي على ابن عمي، واني وابن عمي على", completions: { correct: "الغريب", wrong: ["العدو", "الصديق", "الجار"] }, type: 'proverb', difficulty: 0 },
  { text: "اليتيم يبجي و", completions: { correct: "يسكت", wrong: ["ينام", "يضحك", "ياكل"] }, type: 'proverb', difficulty: 2 },
  { text: "الفلوس تجيب", completions: { correct: "العروس", wrong: ["السيف", "الصديق", "الحظ"] }, type: 'proverb', difficulty: 0 },
  { text: "لو بيه خير ما عافه", completions: { correct: "الطير", wrong: ["الذيب", "الصياد", "الناس"] }, type: 'proverb', difficulty: 1 },
  { text: "يا غريب كون", completions: { correct: "أديب", wrong: ["عاقل", "فطن", "كريم"] }, type: 'proverb', difficulty: 0 },
  { text: "تعب الماعنده حظ، يتعب و", completions: { correct: "يكعد", wrong: ["يتبهدل", "ينام", "يخسر"] }, type: 'proverb', difficulty: 2 },
  { text: "اسأل مجرب ولا تسأل", completions: { correct: "حكيم", wrong: ["طبيب", "عالم", "جاهل"] }, type: 'proverb', difficulty: 0 },
  { text: "الما يعرف يتدلل", completions: { correct: "يكعد", wrong: ["يبجي", "يروح", "يسكت"] }, type: 'proverb', difficulty: 2 },
  { text: "عريان لاثك بلـ", completions: { correct: "مكدي", wrong: ["حافي", "جوعان", "تعبان"] }, type: 'proverb', difficulty: 2 },
  { text: "تيتي تيتي، مثل ما رحتي", completions: { correct: "جيتي", wrong: ["بجيتي", "رجعتي", "خسرتي"] }, type: 'proverb', difficulty: 1 },
  { text: "الرخيص مخيس والزين", completions: { correct: "غالي", wrong: ["طيب", "حلو", "مقبول"] }, type: 'proverb', difficulty: 1 },
  { text: "العين ما تعلى على", completions: { correct: "الحاجب", wrong: ["الراس", "الجفن", "الخشم"] }, type: 'proverb', difficulty: 0 }
];
