import { ProverbData } from './types';
export const LEVANT_PROVERBS_2: ProverbData[] = [
  { text: "يا جبل ما يهزك", completions: { correct: "ريح", wrong: ["مطر", "رعد", "برق"] }, type: 'proverb', difficulty: 0 },
  { text: "الدم ما بيصير", completions: { correct: "مي", wrong: ["عصير", "شاي", "زيت"] }, type: 'proverb', difficulty: 0 },
  { text: "من برا رخام ومن جوا", completions: { correct: "سخام", wrong: ["ظلام", "فحم", "عظام"] }, type: 'proverb', difficulty: 1 },
  { text: "دود الخل منه وفيه، واللي بياكل العصي مش متل اللي", completions: { correct: "بيعدها", wrong: ["بينضربها", "بيكسرها", "بيحملها"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي ما بيعرف الصقر", completions: { correct: "بيشويه", wrong: ["بيربيه", "بيطيره", "بيصيده"] }, type: 'proverb', difficulty: 0 },
  { text: "ابنك الصغير ربيه، وابنك الكبير", completions: { correct: "خاويه", wrong: ["علمه", "ضربه", "جوزه"] }, type: 'wisdom', difficulty: 1 },
  { text: "خلي العسل بجراره لتغلى", completions: { correct: "أسعاره", wrong: ["أيامه", "أسواقه", "أعوامه"] }, type: 'proverb', difficulty: 1 },
  { text: "طنجرة ولقت", completions: { correct: "غطاها", wrong: ["نارها", "أكلها", "صاحبها"] }, type: 'proverb', difficulty: 0 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["براها", "جانبها", "تحتها"] }, type: 'proverb', difficulty: 0 },
  { text: "بحصة بتسند", completions: { correct: "خابية", wrong: ["جرة", "حائط", "جبل"] }, type: 'proverb', difficulty: 2 },
  { text: "كل ديك على مزبلته", completions: { correct: "صياح", wrong: ["شجاع", "بطل", "ملك"] }, type: 'proverb', difficulty: 0 },
  { text: "الجمرة ما بتحرق إلا محل ما", completions: { correct: "تقع", wrong: ["تطير", "تنام", "تكون"] }, type: 'proverb', difficulty: 1 },
  { text: "حط إيدك بمي باردة", completions: { correct: "وارتاح", wrong: ["ونام", "وكل", "وامشي"] }, type: 'proverb', difficulty: 2 },
  { text: "الغايب عذره", completions: { correct: "معه", wrong: ["بكرا", "فيه", "وراه"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ببطنه مسلة", completions: { correct: "بتنعره", wrong: ["بتوجعه", "بتفضحه", "بتقتله"] }, type: 'proverb', difficulty: 2 },
  { text: "قرد يسليك ولا غزال", completions: { correct: "يبكيك", wrong: ["يضحكك", "ينسيك", "يلهيك"] }, type: 'proverb', difficulty: 1 },
  { text: "إذا بدك تحيره", completions: { correct: "خيره", wrong: ["اسأله", "دوره", "شوره"] }, type: 'proverb', difficulty: 1 },
  { text: "إللي بيته من زجاج، ما يرمي الناس بـ", completions: { correct: "الحجارة", wrong: ["الكلام", "النار", "الماء"] }, type: 'proverb', difficulty: 0 },
  { text: "خليها بالقلب تجرح، ولا تطلع لبرا و", completions: { correct: "تفضح", wrong: ["تدبح", "تجرح", "تندم"] }, type: 'proverb', difficulty: 1 },
  { text: "قالوا للديك صيح، قال كل شي بوقته", completions: { correct: "مليح", wrong: ["منيح", "صحيح", "عجيب"] }, type: 'proverb', difficulty: 1 },
  { text: "على قد بساطك مد", completions: { correct: "رجليك", wrong: ["إيديك", "طولك", "حالك"] }, type: 'proverb', difficulty: 0 },
  { text: "متل الأطرش بـ", completions: { correct: "الزفة", wrong: ["الحفلة", "السوق", "الشارع"] }, type: 'proverb', difficulty: 0 },
  { text: "يا رايح كتر الـ", completions: { correct: "فضايح", wrong: ["ملايح", "نصايح", "روايح"] }, type: 'proverb', difficulty: 1 },
  { text: "بعد ما شاب ودوه عالـ", completions: { correct: "كُتاب", wrong: ["مدرسة", "جامعة", "مسجد"] }, type: 'proverb', difficulty: 0 },
  { text: "حساب السرايا ما طابق حساب", completions: { correct: "القرايا", wrong: ["الحكايا", "البقايا", "الخفايا"] }, type: 'proverb', difficulty: 2 },
  { text: "يا مستعجل وقّف لـ", completions: { correct: "أقلك", wrong: ["أمشي", "أسمع", "أشوف"] }, type: 'proverb', difficulty: 1 },
  { text: "لا تنام بين القبور ولا تشوف", completions: { correct: "منامات وحشة", wrong: ["أشباح", "كوابيس", "أحلام سيئة"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور بالإيد ولا عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "السما"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما إلو قديم، ما إلو", completions: { correct: "جديد", wrong: ["قيمة", "ماضي", "مستقبل"] }, type: 'wisdom', difficulty: 1 },
  { text: "ما بيحك جلدك متل", completions: { correct: "ضفرك", wrong: ["إيدك", "صاحبك", "جارك"] }, type: 'proverb', difficulty: 0 },
  { text: "مين شافوه الصبح، قال الفلوس", completions: { correct: "بالربح", wrong: ["بالكيس", "بالدار", "بالإيد"] }, type: 'proverb', difficulty: 2 },
  { text: "من كترت طباخينه، شاطت", completions: { correct: "طبخته", wrong: ["أكلته", "كعكته", "ناره"] }, type: 'proverb', difficulty: 1 },
  { text: "الكلمة اللي بتستحي منها،", completions: { correct: "بدها", wrong: ["قولها", "خبيها", "انساها"] }, type: 'wisdom', difficulty: 2 },
  { text: "يلي بياكل العصي، مش متل يلي", completions: { correct: "بيعدها", wrong: ["بيضربها", "بيكسرها", "بينساها"] }, type: 'proverb', difficulty: 1 }
];
