import { ProverbData } from './types';
export const MEGA_PROVERBS_5: ProverbData[] = [
  { text: "أجود من", completions: { correct: "حاتم", wrong: ["طارق", "قيس", "عنترة"] }, type: 'saying', difficulty: 1 },
  { text: "أشجع من", completions: { correct: "عنترة", wrong: ["أسد", "فارس", "نمر"] }, type: 'saying', difficulty: 1 },
  { text: "أطعم من", completions: { correct: "الأم", wrong: ["الشهد", "العسل", "السكر"] }, type: 'proverb', difficulty: 2 },
  { text: "لا تكن صلبا فتكسر ولا لينا", completions: { correct: "فتعصر", wrong: ["فتهان", "فتسقط", "فتضيع"] }, type: 'wisdom', difficulty: 1 },
  { text: "الجزاء من جنس", completions: { correct: "العمل", wrong: ["القول", "الفعل", "النية"] }, type: 'wisdom', difficulty: 0 },
  { text: "الجار قبل", completions: { correct: "الدار", wrong: ["المال", "الولد", "الأهل"] }, type: 'wisdom', difficulty: 0 },
  { text: "ابن يومين ما يعيش", completions: { correct: "ثلاثة", wrong: ["شهر", "سنة", "عمر"] }, type: 'proverb', difficulty: 1 },
  { text: "ما خاب من استخار ولا ندم من", completions: { correct: "استشار", wrong: ["فكر", "صبر", "تعلم"] }, type: 'wisdom', difficulty: 0 },
  { text: "تاج المروءة", completions: { correct: "التواضع", wrong: ["الصدق", "الكرم", "الحلم"] }, type: 'wisdom', difficulty: 1 },
  { text: "رضا الناس غاية لا", completions: { correct: "تدرك", wrong: ["تتحقق", "تصل", "تعرف"] }, type: 'wisdom', difficulty: 0 },
  { text: "طابور الصباح يعلم", completions: { correct: "النظام", wrong: ["الجد", "العمل", "الطاعة"] }, type: 'proverb', difficulty: 2 },
  { text: "في السفر تعرف أخلاق", completions: { correct: "الرجال", wrong: ["الناس", "الأصدقاء", "البشر"] }, type: 'wisdom', difficulty: 1 },
  { text: "إن مع العسر", completions: { correct: "يسرا", wrong: ["فرجا", "رحمة", "خيرا"] }, type: 'wisdom', difficulty: 0 },
  { text: "تفاءلوا بالخير", completions: { correct: "تجدوه", wrong: ["تلقوه", "تحصدوه", "تروه"] }, type: 'wisdom', difficulty: 0 },
  { text: "عاشر القوم أربعين يوما إما أن تصير منهم أو", completions: { correct: "ترحل عنهم", wrong: ["يكرهوك", "تعاديهم", "تهرب منهم"] }, type: 'wisdom', difficulty: 2 },
  { text: "الحسود لا", completions: { correct: "يسود", wrong: ["ينتصر", "يفوز", "ينجح"] }, type: 'wisdom', difficulty: 1 },
  { text: "لا تبك على اللبن", completions: { correct: "المسكوب", wrong: ["الضائع", "الفاسد", "الحامض"] }, type: 'proverb', difficulty: 0 },
  { text: "من تدخل فيما لا يعنيه لقي ما لا", completions: { correct: "يرضيه", wrong: ["يعجبه", "يهواه", "يحبه"] }, type: 'wisdom', difficulty: 0 },
  { text: "صديقك من صدقك لا من", completions: { correct: "صدقك", wrong: ["كذبك", "نافقك", "جامل"] }, type: 'wisdom', difficulty: 2 },
  { text: "ما حك جلدك مثل", completions: { correct: "ظفرك", wrong: ["أخيك", "صديقك", "مالك"] }, type: 'wisdom', difficulty: 0 },
  { text: "السراج يضيء للناس ويحرق", completions: { correct: "نفسه", wrong: ["بيته", "زيت", "صاحبه"] }, type: 'wisdom', difficulty: 1 },
  { text: "اتق شر من أحسنت", completions: { correct: "إليه", wrong: ["له", "معه", "عليه"] }, type: 'wisdom', difficulty: 0 },
  { text: "رب أخ لك لم تلده", completions: { correct: "أمك", wrong: ["أيامك", "عيلتك", "أختك"] }, type: 'wisdom', difficulty: 0 },
  { text: "عقل المرأة في", completions: { correct: "جمالها", wrong: ["لسانها", "قلبها", "عينها"] }, type: 'wisdom', difficulty: 2 },
  { text: "جمال الرجل في", completions: { correct: "عقله", wrong: ["ماله", "نسبه", "وجهه"] }, type: 'wisdom', difficulty: 2 },
  { text: "الصيت ولا", completions: { correct: "الغنى", wrong: ["الفقر", "العمى", "الموت"] }, type: 'proverb', difficulty: 1 },
  { text: "أول الشجرة", completions: { correct: "بذرة", wrong: ["ورقة", "غصن", "ثمرة"] }, type: 'wisdom', difficulty: 0 },
  { text: "قطرة على قطرة تعمل", completions: { correct: "غديرا", wrong: ["بحرا", "نهرا", "بركة"] }, type: 'wisdom', difficulty: 1 },
  { text: "النار من مستصغر", completions: { correct: "الشرر", wrong: ["الحطب", "الكبريت", "الجمر"] }, type: 'wisdom', difficulty: 1 },
  { text: "في الحركة", completions: { correct: "بركة", wrong: ["صحة", "قوة", "فائدة"] }, type: 'proverb', difficulty: 0 }
];
