import { ProverbData } from './types';
export const MEGA_PROVERBS_4: ProverbData[] = [
  { text: "أعط القوس", completions: { correct: "باريها", wrong: ["راميها", "صانعها", "حاملها"] }, type: 'wisdom', difficulty: 2 },
  { text: "أنجز حر ما", completions: { correct: "وعد", wrong: ["قال", "أراد", "طلب"] }, type: 'wisdom', difficulty: 1 },
  { text: "إن مع اليوم", completions: { correct: "غدا", wrong: ["أمسا", "ليلا", "صباحا"] }, type: 'wisdom', difficulty: 1 },
  { text: "إن غدا لناظره", completions: { correct: "قريب", wrong: ["بعيد", "آت", "جميل"] }, type: 'wisdom', difficulty: 0 },
  { text: "بين حانة ومانة ضاعت", completions: { correct: "لحانا", wrong: ["أموالنا", "عقولنا", "أوقاتنا"] }, type: 'saying', difficulty: 1 },
  { text: "تجري الرياح بما لا تشتهي", completions: { correct: "السفن", wrong: ["الأمواج", "الشواطئ", "الأسماك"] }, type: 'wisdom', difficulty: 0 },
  { text: "حبل الكذب", completions: { correct: "قصير", wrong: ["طويل", "مقطوع", "ضعيف"] }, type: 'wisdom', difficulty: 0 },
  { text: "رب صدفة خير من ألف", completions: { correct: "ميعاد", wrong: ["موعد", "لقاء", "انتظار"] }, type: 'wisdom', difficulty: 0 },
  { text: "رجعت حليمة لعادتها", completions: { correct: "القديمة", wrong: ["الأولى", "السيئة", "المجنونة"] }, type: 'saying', difficulty: 0 },
  { text: "رُبّ ضارة", completions: { correct: "نافعة", wrong: ["وخيمة", "قاتلة", "مؤلمة"] }, type: 'wisdom', difficulty: 0 },
  { text: "رجع بخفي", completions: { correct: "حنين", wrong: ["ذئب", "نادم", "ثعلب"] }, type: 'saying', difficulty: 0 },
  { text: "سحابة صيف وتنقشع", completions: { correct: "قريباً", wrong: ["سريعاً", "غداً", "اليوم"] }, type: 'saying', difficulty: 1 },
  { text: "شهد شاهد من", completions: { correct: "أهلها", wrong: ["الناس", "أعدائها", "جيرانها"] }, type: 'wisdom', difficulty: 1 },
  { text: "عصفور في اليد خير من عشرة على", completions: { correct: "الشجرة", wrong: ["الأرض", "الحبل", "السطح"] }, type: 'proverb', difficulty: 0 },
  { text: "عند جهينة الخبر", completions: { correct: "اليقين", wrong: ["الأكيد", "الصحيح", "الكاذب"] }, type: 'saying', difficulty: 1 },
  { text: "فرخ البط", completions: { correct: "عوام", wrong: ["طائر", "سباح", "خائف"] }, type: 'proverb', difficulty: 0 },
  { text: "كل تأخيرة وفيها", completions: { correct: "خيرة", wrong: ["مصلحة", "عبرة", "ندامة"] }, type: 'wisdom', difficulty: 0 },
  { text: "لولا اختلاف الأذواق لبارت", completions: { correct: "السلع", wrong: ["الأسواق", "البضائع", "التجارة"] }, type: 'wisdom', difficulty: 0 },
  { text: "من جد وجد ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نجح", "فرح"] }, type: 'wisdom', difficulty: 0 },
  { text: "من داس على الشوك لا يلم إلا", completions: { correct: "نفسه", wrong: ["غيره", "حبه", "قلبه"] }, type: 'wisdom', difficulty: 0 },
  { text: "من طلب العلا سهر", completions: { correct: "الليالي", wrong: ["الأيام", "النهار", "الشهور"] }, type: 'wisdom', difficulty: 0 },
  { text: "نور على", completions: { correct: "نور", wrong: ["ظلام", "شمس", "قمر"] }, type: 'wisdom', difficulty: 0 },
  { text: "وافق شن", completions: { correct: "طبقة", wrong: ["عقبة", "جبل", "حفنة"] }, type: 'saying', difficulty: 1 },
  { text: "يد الله مع", completions: { correct: "الجماعة", wrong: ["الوحدة", "الصابرين", "القوة"] }, type: 'wisdom', difficulty: 0 },
  { text: "يضحك كثيرا من يضحك", completions: { correct: "أخيرا", wrong: ["أولا", "مبكرا", "دائما"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل سر جاوز الاثنين", completions: { correct: "شاع", wrong: ["ضاع", "مات", "ظهر"] }, type: 'wisdom', difficulty: 1 },
  { text: "الطيور على أشكالها", completions: { correct: "تقع", wrong: ["تطير", "تتجمع", "تنزل"] }, type: 'wisdom', difficulty: 0 },
  { text: "الضرورات تبيح", completions: { correct: "المحظورات", wrong: ["الذنوب", "الأخطاء", "الشهوات"] }, type: 'wisdom', difficulty: 0 },
  { text: "الصبر مفتاح", completions: { correct: "الفرج", wrong: ["النجاح", "السعادة", "الكسب"] }, type: 'wisdom', difficulty: 0 },
  { text: "الأعور في بلاد العميان", completions: { correct: "ملك", wrong: ["طبيب", "قائد", "أمير"] }, type: 'proverb', difficulty: 0 }
];
