import { ProverbData } from './types';
export const MEGA_PROVERBS_13: ProverbData[] = [
  { text: "أبرد من", completions: { correct: "الثلج", wrong: ["النار", "الهواء", "الشتاء"] }, type: 'saying', difficulty: 0 },
  { text: "أجمل من", completions: { correct: "القمر", wrong: ["الشمس", "الورد", "الفجر"] }, type: 'saying', difficulty: 0 },
  { text: "إلى أن يبيض", completions: { correct: "الغراب", wrong: ["القط", "الكلب", "الديك"] }, type: 'saying', difficulty: 1 },
  { text: "اللي يشيل قربة مخرومة تخر على", completions: { correct: "راسه", wrong: ["ظهره", "إيده", "رجله"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي في القلب في", completions: { correct: "القلب", wrong: ["الروح", "العين", "الفكر"] }, type: 'proverb', difficulty: 0 },
  { text: "أم سلوم تحكي علوم", completions: { correct: "الناس", wrong: ["الجيران", "الزمن", "الغيب"] }, type: 'proverb', difficulty: 2 },
  { text: "الباب اللي يجيلك منه الريح", completions: { correct: "سده واستريح", wrong: ["افتحه وارتاح", "قفله ونام", "ارمي مفتاحه"] }, type: 'proverb', difficulty: 0 },
  { text: "البياض نصف", completions: { correct: "الحسن", wrong: ["الجمال", "السحر", "الروعة"] }, type: 'saying', difficulty: 1 },
  { text: "التكرار يعلم", completions: { correct: "الحمار", wrong: ["الشطار", "الفاهم", "الكبير"] }, type: 'proverb', difficulty: 0 },
  { text: "الحسود لا", completions: { correct: "يسود", wrong: ["ينتصر", "يربح", "ينجح"] }, type: 'wisdom', difficulty: 0 },
  { text: "الحمي حاميها", completions: { correct: "حراميها", wrong: ["سارقها", "حارسها", "قاضيها"] }, type: 'proverb', difficulty: 0 },
  { text: "الكذب ملح", completions: { correct: "الرجال", wrong: ["الطعام", "الحديث", "الناس"] }, type: 'proverb', difficulty: 1 },
  { text: "النجار بابه", completions: { correct: "مخلع", wrong: ["مكسور", "حديد", "مفقود"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي على راسه بطحة يحسس", completions: { correct: "عليها", wrong: ["بها", "حولها", "جنبها"] }, type: 'proverb', difficulty: 0 },
  { text: "النوم سلطان", completions: { correct: "العين", wrong: ["الجسم", "الروح", "القلب"] }, type: 'saying', difficulty: 0 },
  { text: "اللي يحب النبي", completions: { correct: "يصلي عليه", wrong: ["يطيعه", "يتبعه", "يحبه"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ياكل على ضرسه", completions: { correct: "ينفع نفسه", wrong: ["يشبع بطنه", "يثقل نومه", "يريح عقله"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي بيته من إزاز ما يحدفش الناس بـ", completions: { correct: "الطوب", wrong: ["الورد", "الكلام", "النار"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي تشوفه بعينك", completions: { correct: "صدقه", wrong: ["انكره", "كذبه", "انساه"] }, type: 'proverb', difficulty: 0 },
  { text: "امسك الخشب حسن لا", completions: { correct: "تتحسد", wrong: ["تنكسر", "تسقط", "تموت"] }, type: 'proverb', difficulty: 0 },
  { text: "أهل مكة أدرى", completions: { correct: "بشعابها", wrong: ["بطرقها", "بحاراتها", "بناسها"] }, type: 'wisdom', difficulty: 0 },
  { text: "تيتي تيتي، متل ما رحتي", completions: { correct: "اجيتي", wrong: ["نمتي", "مشيتي", "قعدتي"] }, type: 'proverb', difficulty: 0 },
  { text: "حبل الكذب", completions: { correct: "قصير", wrong: ["مقطوع", "طويل", "ضعيف"] }, type: 'wisdom', difficulty: 0 },
  { text: "داري على شمعتك", completions: { correct: "تقيد", wrong: ["تنور", "تطفي", "تولع"] }, type: 'proverb', difficulty: 0 },
  { text: "ديل الكلب عمره ما", completions: { correct: "يتعدل", wrong: ["يوقف", "ينكسر", "يكبر"] }, type: 'proverb', difficulty: 0 },
  { text: "زي القطط بسبع", completions: { correct: "أرواح", wrong: ["جوايع", "عماير", "أسنان"] }, type: 'proverb', difficulty: 0 },
  { text: "سبع صنايع والبخت", completions: { correct: "ضايع", wrong: ["مايل", "غايب", "نايم"] }, type: 'proverb', difficulty: 0 },
  { text: "طاسة ضايعة", completions: { correct: "فيها", wrong: ["عليها", "جنبها", "تحتها"] }, type: 'proverb', difficulty: 1 },
  { text: "ضربني وبكى سبقني", completions: { correct: "واشتكى", wrong: ["وجرى", "وقال", "وراح"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور في الايد أحسن من عشرة على", completions: { correct: "الشجرة", wrong: ["السما", "الأرض", "في الجو"] }, type: 'proverb', difficulty: 0 }
];
