import { ProverbData } from './types';
export const MEGA_PROVERBS_11: ProverbData[] = [
  { text: "أجود الخيل ما يرى", completions: { correct: "سائسه", wrong: ["ظله", "نوره", "صاحبه"] }, type: 'proverb', difficulty: 1 },
  { text: "أعقل الناس أقدرهم على", completions: { correct: "المداراة", wrong: ["المعاناة", "المقاتلة", "الخصام"] }, type: 'wisdom', difficulty: 1 },
  { text: "أغنى الناس من قنع بما", completions: { correct: "رزقه الله", wrong: ["كسبت يداه", "ورثه", "حصله"] }, type: 'wisdom', difficulty: 0 },
  { text: "أكثر الناس أذى من لا", completions: { correct: "يؤمن شره", wrong: ["يؤمن جانبه", "يؤتمن", "يصدق"] }, type: 'wisdom', difficulty: 1 },
  { text: "أمّن الحجر قبل أن تأمن", completions: { correct: "البشر", wrong: ["الناس", "العدو", "الزمن"] }, type: 'wisdom', difficulty: 1 },
  { text: "أن توقد شمعة خير من أن تلعن", completions: { correct: "الظلام", wrong: ["الزمن", "الناس", "الحظ"] }, type: 'wisdom', difficulty: 0 },
  { text: "أنفذ من رصاصة في", completions: { correct: "القلب", wrong: ["البحر", "الجبل", "الهواء"] }, type: 'wisdom', difficulty: 1 },
  { text: "إياك ومؤاخاة الأحمق فإنه يريد أن ينفعك", completions: { correct: "فيضرك", wrong: ["فيهلكك", "فيقتلك", "فيحبطك"] }, type: 'wisdom', difficulty: 1 },
  { text: "تعب العمر يذهب في", completions: { correct: "لحظة", wrong: ["دقيقة", "ساعة", "طرفة"] }, type: 'wisdom', difficulty: 0 },
  { text: "ثمرة الأدب العقل الممدوح وثمرة الجهل", completions: { correct: "الذم", wrong: ["الحزن", "الكبر", "النار"] }, type: 'wisdom', difficulty: 2 },
  { text: "حبل الكذب قصير وإن", completions: { correct: "طال", wrong: ["كبر", "امتد", "تضخم"] }, type: 'wisdom', difficulty: 0 },
  { text: "رب سكوت أبلغ من", completions: { correct: "كلام", wrong: ["رد", "قول", "صراخ"] }, type: 'wisdom', difficulty: 0 },
  { text: "رصاصة الطائشة لا", completions: { correct: "تخطئ", wrong: ["تصيب", "تقتل", "ترحم"] }, type: 'wisdom', difficulty: 1 },
  { text: "زر النبى ولا تقطع", completions: { correct: "حديثه", wrong: ["قوله", "دعاءه", "كلامه"] }, type: 'wisdom', difficulty: 1 },
  { text: "سلاح اللئيم", completions: { correct: "قبح الكلام", wrong: ["شره", "فعله", "كذبه"] }, type: 'wisdom', difficulty: 1 },
  { text: "شاور من هواك وخالفه", completions: { correct: "ترشد", wrong: ["تنجو", "تسلم", "تربح"] }, type: 'wisdom', difficulty: 1 },
  { text: "صلة الرحم تزيد في", completions: { correct: "العمر", wrong: ["المال", "الجاه", "الصحة"] }, type: 'wisdom', difficulty: 0 },
  { text: "عثرة القدم أسلم من عثرة", completions: { correct: "اللسان", wrong: ["الكلمة", "الشأن", "القول"] }, type: 'wisdom', difficulty: 0 },
  { text: "غنى النفس خير من", completions: { correct: "غنى المال", wrong: ["غنى العقل", "السلطان", "الجاه"] }, type: 'wisdom', difficulty: 0 },
  { text: "قول الحق لم يدع لي", completions: { correct: "صديقا", wrong: ["رفيقا", "حبيبا", "أخا"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل إناء بالذي فيه", completions: { correct: "ينضح", wrong: ["يقطر", "يصب", "يفور"] }, type: 'wisdom', difficulty: 0 },
  { text: "لا تكن رطبا فتعصر ولا صلبا", completions: { correct: "فتكسر", wrong: ["فتهان", "فتضيع", "فتترك"] }, type: 'wisdom', difficulty: 1 },
  { text: "من تأنى أدرك ما", completions: { correct: "تمنى", wrong: ["أراد", "طلب", "حلم"] }, type: 'wisdom', difficulty: 0 },
  { text: "من جد وجد ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نجح", "استراح"] }, type: 'wisdom', difficulty: 0 },
  { text: "ما طار طير وارتفع إلا كما طار", completions: { correct: "وقع", wrong: ["نزل", "هوى", "تحطم"] }, type: 'wisdom', difficulty: 0 },
  { text: "خير جليس في الزمان", completions: { correct: "كتاب", wrong: ["صديق", "حبيب", "مال"] }, type: 'wisdom', difficulty: 0 },
  { text: "الوقت كالسيف إن لم تقطعه", completions: { correct: "قطعك", wrong: ["أخذك", "كسرك", "رحل"] }, type: 'wisdom', difficulty: 0 },
  { text: "العقل السليم في الجسم", completions: { correct: "السليم", wrong: ["الصحيح", "القوي", "الرشيق"] }, type: 'wisdom', difficulty: 0 },
  { text: "رضا الناس غاية لا", completions: { correct: "تدرك", wrong: ["تصل", "تنتهي", "مستحيلة"] }, type: 'wisdom', difficulty: 0 },
  { text: "عند الامتحان يكرم المرء أو", completions: { correct: "يهان", wrong: ["يسقط", "يسأل", "يختبر"] }, type: 'wisdom', difficulty: 0 }
];
