import { ProverbData } from './types';
export const MEGA_PROVERBS_8: ProverbData[] = [
  { text: "أبرد من مية", completions: { correct: "طوبة", wrong: ["شبط", "أمشير", "برمهات"] }, type: 'proverb', difficulty: 2 },
  { text: "اللي ياكل لوحده", completions: { correct: "يزور", wrong: ["يشبع", "يمرض", "يفرح"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يشوفش من الغربال يبقى", completions: { correct: "أعمى", wrong: ["أطرش", "مجنون", "أهبل"] }, type: 'proverb', difficulty: 0 },
  { text: "الناس خيبتها السبت والحد وأنا خيبتي ما وردت على", completions: { correct: "حد", wrong: ["بلد", "أحد", "بشر"] }, type: 'proverb', difficulty: 1 },
  { text: "جه يكحلها", completions: { correct: "عماها", wrong: ["جرحها", "كسرها", "بوظها"] }, type: 'proverb', difficulty: 0 },
  { text: "حجة البليد مسح", completions: { correct: "السبورة", wrong: ["الدفتر", "الطاولة", "العين"] }, type: 'proverb', difficulty: 0 },
  { text: "ديل الكلب عمره ما يتعدل ولو علقوا فيه", completions: { correct: "قالب", wrong: ["حبل", "عظمة", "لحمة"] }, type: 'proverb', difficulty: 1 },
  { text: "ربنا عرفوه", completions: { correct: "بالعقل", wrong: ["بالعين", "بالقلب", "بالروح"] }, type: 'wisdom', difficulty: 0 },
  { text: "عتاب الندل", completions: { correct: "اجتنابه", wrong: ["ضربه", "شتمه", "طرده"] }, type: 'wisdom', difficulty: 1 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["إيديك", "نفسك", "طولك"] }, type: 'proverb', difficulty: 0 },
  { text: "كل تأخيرة وفيها", completions: { correct: "خيرة", wrong: ["مصلحة", "عبرة", "درس"] }, type: 'proverb', difficulty: 0 },
  { text: "لبس البوصة تبقى", completions: { correct: "عروسة", wrong: ["حلوة", "زينة", "ملكة"] }, type: 'proverb', difficulty: 0 },
  { text: "ما يعجبش العجب ولا الصيام في", completions: { correct: "رجب", wrong: ["شعبان", "رمضان", "شوال"] }, type: 'proverb', difficulty: 0 },
  { text: "يا قاعدين يكفيكوا شر", completions: { correct: "الجايين", wrong: ["الرايحين", "الطالعين", "النازلين"] }, type: 'proverb', difficulty: 0 },
  { text: "يا مأمنة للرجال يا مأمنة للمية في", completions: { correct: "الغربال", wrong: ["الكوز", "الصحن", "القلة"] }, type: 'proverb', difficulty: 1 },
  { text: "يا واخد القرد على ماله بكرة يروح المال ويقعد القرد على", completions: { correct: "حاله", wrong: ["قلبك", "راسك", "كتفك"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي تخاف منه مافيش أحسن", completions: { correct: "منه", wrong: ["غيره", "مثله", "زيه"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي ما يعرفش يقول", completions: { correct: "عدس", wrong: ["فول", "قشطة", "عسل"] }, type: 'proverb', difficulty: 0 },
  { text: "امسك المجنون لا يجيلك أجن", completions: { correct: "منه", wrong: ["عليه", "فيه", "زيه"] }, type: 'proverb', difficulty: 1 },
  { text: "إن حبتك حية اتطوق", completions: { correct: "بيها", wrong: ["منها", "معها", "العب بيها"] }, type: 'proverb', difficulty: 2 },
  { text: "بكرة النقبا تقابل", completions: { correct: "بعضها", wrong: ["الناس", "الوشوش", "الأعداء"] }, type: 'proverb', difficulty: 2 },
  { text: "تيجي مع الهبل", completions: { correct: "دبل", wrong: ["جوز", "فرد", "كثير"] }, type: 'proverb', difficulty: 1 },
  { text: "جحا أولى بلحم", completions: { correct: "ثوره", wrong: ["كبشه", "نفسه", "عجله"] }, type: 'proverb', difficulty: 0 },
  { text: "خيراً تعمل شراً", completions: { correct: "تلقى", wrong: ["تحصد", "تجد", "تأخذ"] }, type: 'wisdom', difficulty: 0 },
  { text: "دخان عماك ولا برد", completions: { correct: "شفاك", wrong: ["قتلك", "أذاك", "موتك"] }, type: 'proverb', difficulty: 2 },
  { text: "زي الفريك ما يحبش", completions: { correct: "شريك", wrong: ["جار", "صاحب", "ضرة"] }, type: 'proverb', difficulty: 1 },
  { text: "العتب على", completions: { correct: "النظر", wrong: ["العقل", "القلب", "الفهم"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يشوف من الغربال يبقى", completions: { correct: "أعمى", wrong: ["أهبل", "مجنون", "أطرش"] }, type: 'proverb', difficulty: 0 },
  { text: "على قد بساطك مد", completions: { correct: "رجليك", wrong: ["إيديك", "جسمك", "ظهرك"] }, type: 'proverb', difficulty: 0 },
  { text: "في الوش مراية وفي القفا", completions: { correct: "سلاية", wrong: ["كذابة", "نصابة", "حكاية"] }, type: 'proverb', difficulty: 1 }
];
