import { ProverbData } from './types';
export const MEGA_PROVERBS_3: ProverbData[] = [
  { text: "أعط الخباز خبزه ولو أكل", completions: { correct: "نصفه", wrong: ["كله", "ثلثه", "ربعه"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يطول العنب، حامض عنه", completions: { correct: "يقول", wrong: ["يهرب", "يلقي", "يضحك"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يده في المية مش زي اللي يده في", completions: { correct: "النار", wrong: ["الهواء", "التراب", "الجليد"] }, type: 'proverb', difficulty: 0 },
  { text: "يخلق من الشبه", completions: { correct: "أربعين", wrong: ["كثير", "ثلاثين", "خمسين"] }, type: 'proverb', difficulty: 0 },
  { text: "قرد يسليك ولا غزال", completions: { correct: "يبكيك", wrong: ["يهرب", "يضحكك", "يمرض"] }, type: 'proverb', difficulty: 1 },
  { text: "إذا قلّ ماء الوجه قلّ", completions: { correct: "حياؤه", wrong: ["صدقه", "خوفه", "أمله"] }, type: 'wisdom', difficulty: 1 },
  { text: "ليس كل ما يلمع", completions: { correct: "ذهباً", wrong: ["فضة", "ألماساً", "حديداً"] }, type: 'wisdom', difficulty: 0 },
  { text: "الغاية تبرر", completions: { correct: "الوسيلة", wrong: ["النهاية", "الهدف", "الطريق"] }, type: 'wisdom', difficulty: 0 },
  { text: "العتب على", completions: { correct: "النظر", wrong: ["السمع", "الصبر", "الصديق"] }, type: 'proverb', difficulty: 0 },
  { text: "كما تدين", completions: { correct: "تدان", wrong: ["تحاسب", "تعاقب", "تسامح"] }, type: 'wisdom', difficulty: 0 },
  { text: "يد واحدة لا", completions: { correct: "تصفق", wrong: ["ترفع", "تعمل", "تزرع"] }, type: 'proverb', difficulty: 0 },
  { text: "لا يفل الحديد إلا", completions: { correct: "الحديد", wrong: ["النار", "السيف", "الصبر"] }, type: 'wisdom', difficulty: 0 },
  { text: "السكوت علامة", completions: { correct: "الرضا", wrong: ["الضعف", "الخوف", "الحزن"] }, type: 'wisdom', difficulty: 0 },
  { text: "علمناهم الشحادة، سبقونا على", completions: { correct: "الأبواب", wrong: ["الطريق", "الجوامع", "البيوت"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي بيتجوز أمي بقله يا", completions: { correct: "عمي", wrong: ["أبي", "خالي", "سيدي"] }, type: 'proverb', difficulty: 0 },
  { text: "أقرع وبتشيرط على", completions: { correct: "الحلاق", wrong: ["الخياط", "الدكتور", "الاسواق"] }, type: 'proverb', difficulty: 1 },
  { text: "إيش ياخد الريح من", completions: { correct: "البلاط", wrong: ["التراب", "الشجر", "الورق"] }, type: 'proverb', difficulty: 1 },
  { text: "مية قلبة ولا رحلة", completions: { correct: "كلب", wrong: ["قطة", "موت", "ألم"] }, type: 'proverb', difficulty: 2 },
  { text: "إللي بيضربك إضربه، ما أنت أعرج وإللي بيعطيك", completions: { correct: "حرمه", wrong: ["حبه", "كثره", "آكله"] }, type: 'proverb', difficulty: 2 },
  { text: "الباب اللي يجيك منه الريح", completions: { correct: "سده واستريح", wrong: ["ادخله", "افتحه", "اكسره"] }, type: 'proverb', difficulty: 0 },
  { text: "نام على الجنب اللي", completions: { correct: "يريحك", wrong: ["يوجعك", "يتعبك", "يوقظك"] }, type: 'proverb', difficulty: 0 },
  { text: "المال السايب يعلم", completions: { correct: "السرقة", wrong: ["البخل", "الكسل", "الغباء"] }, type: 'proverb', difficulty: 0 },
  { text: "حبيبك يبلع لك الزلط، وعدوك يتمنى لك", completions: { correct: "الغلط", wrong: ["الموت", "التعب", "السقوط"] }, type: 'proverb', difficulty: 0 },
  { text: "كل فولة ولها", completions: { correct: "كيال", wrong: ["أكّال", "طباخ", "بائع"] }, type: 'proverb', difficulty: 1 },
  { text: "امسك الخشب حسن لا", completions: { correct: "تتحسد", wrong: ["تنكسر", "تنصدم", "تحترق"] }, type: 'proverb', difficulty: 0 },
  { text: "يا رايح كتر", completions: { correct: "الملايح", wrong: ["الفضايح", "الذبايح", "الروايح"] }, type: 'proverb', difficulty: 1 },
  { text: "يا بخت من بكاني وبكى عليا ولا ضحكني وضحك", completions: { correct: "الناس عليا", wrong: ["الدنيا", "خلق الله", "الغريب"] }, type: 'proverb', difficulty: 1 },
  { text: "زي الفريك ما يحبش", completions: { correct: "شريك", wrong: ["عدو", "صاحب", "جار"] }, type: 'proverb', difficulty: 1 },
  { text: "الحاجة أم", completions: { correct: "الاختراع", wrong: ["الابداع", "المحاولة", "المعاناة"] }, type: 'wisdom', difficulty: 0 },
  { text: "ابن الوز", completions: { correct: "عوام", wrong: ["عطشان", "طائر", "سباح"] }, type: 'proverb', difficulty: 0 }
];
