import { ProverbData } from './types';
export const MEGA_PROVERBS_7: ProverbData[] = [
  { text: "عنزة الفريج تحب التيس", completions: { correct: "الغريب", wrong: ["القريب", "الصغير", "الكبير"] }, type: 'proverb', difficulty: 1 },
  { text: "عصفور في الإيد ولا عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "الحيط"] }, type: 'proverb', difficulty: 0 },
  { text: "عين الحسود فيها", completions: { correct: "عود", wrong: ["شوك", "حجر", "دم"] }, type: 'proverb', difficulty: 0 },
  { text: "غاب القط، العب يا", completions: { correct: "فار", wrong: ["كلب", "عصفور", "ديك"] }, type: 'proverb', difficulty: 0 },
  { text: "في التأني السلامة، وفي العجلة", completions: { correct: "الندامة", wrong: ["الخسارة", "المصيبة", "الموت"] }, type: 'wisdom', difficulty: 0 },
  { text: "قالوا للحرامي احلف قال جاني", completions: { correct: "الفرج", wrong: ["القاضي", "الشرطي", "الوقت"] }, type: 'proverb', difficulty: 0 },
  { text: "قرعة تتباها بشعر", completions: { correct: "بنت أختها", wrong: ["بنتها", "جارتها", "صاحبتها"] }, type: 'proverb', difficulty: 1 },
  { text: "قط جاع قام ياكل", completions: { correct: "أولاده", wrong: ["ذيله", "تراب", "عظم"] }, type: 'proverb', difficulty: 1 },
  { text: "كأنك يا أبو زيد ما", completions: { correct: "غزيت", wrong: ["مشيت", "رحت", "نمت"] }, type: 'proverb', difficulty: 0 },
  { text: "كتر الدق بيفك", completions: { correct: "اللحام", wrong: ["المسمار", "الباب", "الحديد"] }, type: 'proverb', difficulty: 1 },
  { text: "كل إناء بالذي فيه", completions: { correct: "ينضح", wrong: ["يقطر", "يصب", "يفور"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل فتاة بأبيها", completions: { correct: "معجبة", wrong: ["متيمة", "مجنونة", "مغرورة"] }, type: 'wisdom', difficulty: 0 },
  { text: "لا تضع كل البيض في سلة", completions: { correct: "واحدة", wrong: ["كبيرة", "صغيرة", "مثقوبة"] }, type: 'wisdom', difficulty: 0 },
  { text: "لا يفل الحديد إلا", completions: { correct: "الحديد", wrong: ["النار", "القوة", "الزمن"] }, type: 'wisdom', difficulty: 0 },
  { text: "لو تجري جري الوحوش غير رزقك ما", completions: { correct: "تحوش", wrong: ["تاخذ", "تمسك", "تذوق"] }, type: 'wisdom', difficulty: 0 },
  { text: "ما يوقع إلا", completions: { correct: "الشاطر", wrong: ["الغبي", "الكسلان", "المريض"] }, type: 'proverb', difficulty: 0 },
  { text: "ما بيحك جلدك إلا", completions: { correct: "ظفرك", wrong: ["إيدك", "صاحبك", "أخوك"] }, type: 'wisdom', difficulty: 0 },
  { text: "مجنون يحكي وعاقل", completions: { correct: "يسمع", wrong: ["يفهم", "يتكلم", "يضحك"] }, type: 'proverb', difficulty: 0 },
  { text: "من جد وجد، ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نجح", "فاز"] }, type: 'wisdom', difficulty: 0 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["عليها", "جنبها", "تحتها"] }, type: 'wisdom', difficulty: 0 },
  { text: "من شافك بعين شوفه", completions: { correct: "باثنتين", wrong: ["بثلاث", "بأربع", "بعشر"] }, type: 'proverb', difficulty: 1 },
  { text: "نام على الجنب اللي", completions: { correct: "يريحك", wrong: ["يوجعك", "أتعبك", "ينيمك"] }, type: 'proverb', difficulty: 0 },
  { text: "هيك مضبطة بدها هيك", completions: { correct: "ختم", wrong: ["ورقة", "توقيع", "قلم"] }, type: 'proverb', difficulty: 1 },
  { text: "وش جاب لجاب", completions: { correct: "الفرق شاسع", wrong: ["وش جاب لي", "من جاب ومين", "يا غافل الك الله"] }, type: 'proverb', difficulty: 2 },
  { text: "وردة من كل", completions: { correct: "بستان", wrong: ["لون", "نوع", "شجرة"] }, type: 'saying', difficulty: 0 },
  { text: "يا جبل ما يهزك", completions: { correct: "ريح", wrong: ["شجر", "مطر", "رعد"] }, type: 'proverb', difficulty: 0 },
  { text: "يا رايح كتر", completions: { correct: "الملايح", wrong: ["الفضايح", "السلام", "الكلام"] }, type: 'proverb', difficulty: 0 },
  { text: "يا غريب كن", completions: { correct: "أديب", wrong: ["عاقل", "أصيل", "صبور"] }, type: 'wisdom', difficulty: 0 },
  { text: "يدي الحلق للي بلا", completions: { correct: "ودان", wrong: ["أيدي", "رقبة", "شعر"] }, type: 'proverb', difficulty: 0 }
];
