import { ProverbData } from './types';
export const MEGA_PROVERBS_2: ProverbData[] = [
  { text: "أعط الصباح فرصته لكي", completions: { correct: "يغير الأحوال", wrong: ["يبدد الظلام", "يشرق الشمس", "يريح البال"] }, type: 'wisdom', difficulty: 2 },
  { text: "تيتي تيتي زي ما رحتي", completions: { correct: "جيتي", wrong: ["نسيتي", "لقيتي", "مشيتي"] }, type: 'proverb', difficulty: 0 },
  { text: "يا خبر النهاردة بفلوس بكرة يبقى", completions: { correct: "ببلاش", wrong: ["بتراب", "غالي", "سر"] }, type: 'proverb', difficulty: 0 },
  { text: "امشي في جنازة ولا تمشي في", completions: { correct: "جوازة", wrong: ["مشكلة", "زحمة", "خناقة"] }, type: 'proverb', difficulty: 1 },
  { text: "بات مغلوب ولا تبات", completions: { correct: "غالب", wrong: ["ظالم", "زعلان", "قاهر"] }, type: 'wisdom', difficulty: 1 },
  { text: "قالوا الجمل طلع النخلة قلنا آدي الجمل وآدي", completions: { correct: "النخلة", wrong: ["الصحراء", "الطريق", "الشجرة"] }, type: 'proverb', difficulty: 1 },
  { text: "الغاوي ينقط بـ", completions: { correct: "طاقيته", wrong: ["فلوسه", "عينه", "كلامه"] }, type: 'proverb', difficulty: 1 },
  { text: "عشمتني بالحلق خرمت أنا", completions: { correct: "وداني", wrong: ["مناخيري", "إيدي", "ثوبي"] }, type: 'proverb', difficulty: 1 },
  { text: "كأن على رؤوسهم", completions: { correct: "الطير", wrong: ["النار", "الصخر", "الجبل"] }, type: 'saying', difficulty: 1 },
  { text: "الطيور الجارحة لا", completions: { correct: "تغني", wrong: ["تطير", "تنام", "تبكي"] }, type: 'wisdom', difficulty: 2 },
  { text: "لا ناقة لي فيها ولا", completions: { correct: "جمل", wrong: ["فرس", "غنم", "بقرة"] }, type: 'saying', difficulty: 0 },
  { text: "لو تجري جري الوحوش غير رزقك ما", completions: { correct: "تحوش", wrong: ["تأكل", "تجد", "تأخذ"] }, type: 'wisdom', difficulty: 0 },
  { text: "أبطأ من", completions: { correct: "سلحفاة", wrong: ["نملة", "حلزون", "قنفذ"] }, type: 'proverb', difficulty: 1 },
  { text: "الصديق وقت", completions: { correct: "الضيق", wrong: ["الفرح", "الشدة", "الحاجة"] }, type: 'wisdom', difficulty: 0 },
  { text: "عند الامتحان يكرم المرء أو", completions: { correct: "يهان", wrong: ["يظلم", "يسقط", "ينجح"] }, type: 'wisdom', difficulty: 0 },
  { text: "رضا الناس غاية لا", completions: { correct: "تدرك", wrong: ["تصل", "تعرف", "تتحقق"] }, type: 'wisdom', difficulty: 0 },
  { text: "الصبر مفتاح", completions: { correct: "الفرج", wrong: ["الجنة", "النجاح", "السعادة"] }, type: 'wisdom', difficulty: 0 },
  { text: "إذا وقع العجل كثرت", completions: { correct: "سكاكينه", wrong: ["جراحه", "أحزانه", "قتلاه"] }, type: 'proverb', difficulty: 0 },
  { text: "الوقاية خير من", completions: { correct: "العلاج", wrong: ["المرض", "الأطباء", "الدواء"] }, type: 'wisdom', difficulty: 0 },
  { text: "عذر أقبح من", completions: { correct: "ذنب", wrong: ["فعل", "خطيئة", "كذبة"] }, type: 'wisdom', difficulty: 0 },
  { text: "قطعت جهيزة قول كل", completions: { correct: "خطيب", wrong: ["كاذب", "عالم", "متحدث"] }, type: 'saying', difficulty: 2 },
  { text: "سبق السيف", completions: { correct: "العذل", wrong: ["الكلام", "الدم", "الندم"] }, type: 'saying', difficulty: 2 },
  { text: "جزاء", completions: { correct: "سنمار", wrong: ["الخائن", "الظالم", "العدو"] }, type: 'saying', difficulty: 1 },
  { text: "على نفسها جنت", completions: { correct: "براقش", wrong: ["نملة", "قرية", "ناقة"] }, type: 'saying', difficulty: 1 },
  { text: "من طلب العلا سهر", completions: { correct: "الليالي", wrong: ["النهار", "الفجر", "طويلاً"] }, type: 'wisdom', difficulty: 0 },
  { text: "الوقت كالسيف إن لم تقطعه", completions: { correct: "قطعك", wrong: ["كسرك", "قتلك", "ضرك"] }, type: 'wisdom', difficulty: 0 },
  { text: "ما كل ما يتمنى المرء يدركه، تجري الرياح بما لا تشتهي", completions: { correct: "السفن", wrong: ["الطيور", "الأسماك", "الغيوم"] }, type: 'wisdom', difficulty: 0 },
  { text: "لكل داء دواء يستطب به، إلا الحماقة أعيت من", completions: { correct: "يداويها", wrong: ["يعالجها", "يفهمها", "يشفيها"] }, type: 'wisdom', difficulty: 1 },
  { text: "عادت حليمة لعادتها", completions: { correct: "القديمة", wrong: ["السيئة", "الطيبة", "الجديدة"] }, type: 'proverb', difficulty: 0 },
  { text: "القناعة كنز لا", completions: { correct: "يفنى", wrong: ["يسرق", "يندثر", "يضيع"] }, type: 'wisdom', difficulty: 0 },
  { text: "يا غريب كن", completions: { correct: "أديبا", wrong: ["قويا", "شجاعا", "حذرا"] }, type: 'wisdom', difficulty: 0 }
];
