import { ProverbData } from './types';
export const MEGA_PROVERBS_1: ProverbData[] = [
  { text: "اللي ما يعرف الطير", completions: { correct: "يشويه", wrong: ["يصيده", "يربيه", "يفكه"] }, type: 'proverb', difficulty: 0 },
  { text: "أعور ويقود", completions: { correct: "عميان", wrong: ["مجانين", "مبصرين", "طرشان"] }, type: 'proverb', difficulty: 1 },
  { text: "البعيد عن العين بعيد عن", completions: { correct: "القلب", wrong: ["البال", "الخاطر", "العقل"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي استحوا", completions: { correct: "ماتوا", wrong: ["ناموا", "هربوا", "خافوا"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي على راسه بطحة يحسس", completions: { correct: "عليها", wrong: ["تحتها", "جنبها", "فوقها"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي في القدر تطلعه الـ", completions: { correct: "مغرفة", wrong: ["معلقة", "شرحة", "نار"] }, type: 'proverb', difficulty: 1 },
  { text: "النجار بابه", completions: { correct: "مخلع", wrong: ["مكسور", "قوي", "حديد"] }, type: 'proverb', difficulty: 0 },
  { text: "بعد ما شاب ودوه", completions: { correct: "الكتاب", wrong: ["المدرسة", "الجامعة", "الحضانة"] }, type: 'proverb', difficulty: 0 },
  { text: "حاميها", completions: { correct: "حراميها", wrong: ["قاضيها", "سارقها", "حارسها"] }, type: 'proverb', difficulty: 0 },
  { text: "دخول الحمام مش زي", completions: { correct: "خروجه", wrong: ["دفعته", "نظافته", "أجرته"] }, type: 'proverb', difficulty: 0 },
  { text: "ديل الكلب عمره ما", completions: { correct: "ينعدل", wrong: ["يطول", "يقصر", "يكبر"] }, type: 'proverb', difficulty: 0 },
  { text: "زي القطط بسبع", completions: { correct: "أرواح", wrong: ["عيون", "أسنان", "رجول"] }, type: 'proverb', difficulty: 0 },
  { text: "ضربني وبكى، سبقني و", completions: { correct: "اشتكى", wrong: ["جرى", "بكى", "ادعى"] }, type: 'proverb', difficulty: 0 },
  { text: "عصفور في اليد خير من عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "الحبل"] }, type: 'proverb', difficulty: 0 },
  { text: "عمر الدم ما يبقى", completions: { correct: "ميه", wrong: ["شاي", "عصير", "قهوة"] }, type: 'proverb', difficulty: 0 },
  { text: "في التأني السلامة وفي العجلة", completions: { correct: "الندامة", wrong: ["الخسارة", "الموت", "الندم"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل ديك على مزبلته", completions: { correct: "صياح", wrong: ["بطل", "ملك", "أمير"] }, type: 'proverb', difficulty: 0 },
  { text: "كل فتاة بأبيها", completions: { correct: "معجبة", wrong: ["مغرمة", "سعيدة", "فخورة"] }, type: 'wisdom', difficulty: 0 },
  { text: "مجنون رمى حجر في بير، مية عاقل ما", completions: { correct: "يطلعوه", wrong: ["يفهموه", "يعرفوه", "يصدقوه"] }, type: 'proverb', difficulty: 1 },
  { text: "ما طار طير وارتفع إلا كما طار", completions: { correct: "وقع", wrong: ["نزل", "انكسر", "هبط"] }, type: 'wisdom', difficulty: 0 },
  { text: "مراية الحب", completions: { correct: "عميا", wrong: ["كاذبة", "ساطعة", "مكسورة"] }, type: 'proverb', difficulty: 0 },
  { text: "من برا هالله هالله ومن جوا يعلم", completions: { correct: "الله", wrong: ["الناس", "القلب", "الشيطان"] }, type: 'proverb', difficulty: 0 },
  { text: "من جد وجد ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نام", "ربح"] }, type: 'wisdom', difficulty: 0 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["عليها", "تحتها", "جنبها"] }, type: 'wisdom', difficulty: 0 },
  { text: "من طين بلة، ومن طين", completions: { correct: "جرة", wrong: ["قلة", "زلة", "علة"] }, type: 'proverb', difficulty: 2 },
  { text: "هم يبكي وهم", completions: { correct: "يضحك", wrong: ["يفرح", "يسعد", "يقتل"] }, type: 'proverb', difficulty: 0 },
  { text: "وردة في بستان ولا شوكة في", completions: { correct: "القلب", wrong: ["العين", "اليد", "الرجل"] }, type: 'wisdom', difficulty: 1 },
  { text: "يخلق من الشبه", completions: { correct: "أربعين", wrong: ["عشرين", "مية", "ألف"] }, type: 'proverb', difficulty: 0 },
  { text: "يا بخت من وفق راسين في", completions: { correct: "الحلال", wrong: ["الخير", "الحرام", "الشر"] }, type: 'proverb', difficulty: 0 },
  { text: "يدي الحلق للي بلا", completions: { correct: "ودان", wrong: ["رقبة", "راس", "عقل"] }, type: 'proverb', difficulty: 0 },
  { text: "ابن الوز", completions: { correct: "عوام", wrong: ["طواش", "سريع", "غواص"] }, type: 'proverb', difficulty: 0 },
  { text: "الغايب عذره", completions: { correct: "معه", wrong: ["بكرا", "وراه", "فيه"] }, type: 'proverb', difficulty: 0 },
  { text: "الكلمة اللي تستحي منها", completions: { correct: "بدها", wrong: ["قولها", "خبيها", "انساها"] }, type: 'wisdom', difficulty: 2 },
  { text: "الكلب اللي بينبح ما", completions: { correct: "بيعض", wrong: ["بياكل", "بينام", "بيهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يلسعه الشوربة ينفخ في", completions: { correct: "الزبادي", wrong: ["الميه", "اللبن", "الأكل"] }, type: 'proverb', difficulty: 0 },
  { text: "حبك برج العقرب وأنا برج", completions: { correct: "الجدي", wrong: ["الأسد", "الميزان", "الثور"] }, type: 'saying', difficulty: 2 },
  { text: "يا قاعدين يكفيكو شر", completions: { correct: "الجايين", wrong: ["الطالعين", "النازلين", "المبسوطين"] }, type: 'proverb', difficulty: 0 }
];
