import { ProverbData } from './types';
export const MEGA_PROVERBS_14: ProverbData[] = [
  { text: "أجود ما قيل في العتاب", completions: { correct: "السكوت", wrong: ["الكلام", "الصراخ", "البكاء"] }, type: 'wisdom', difficulty: 1 },
  { text: "اللي ما يشوف من الغربال", completions: { correct: "أعمى", wrong: ["أهبل", "أطرش", "مجنون"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي مايعرفش يقول", completions: { correct: "عدس", wrong: ["فول", "طعمية", "لوبيا"] }, type: 'proverb', difficulty: 0 },
  { text: "ألف قلته ولا", completions: { correct: "سدحته", wrong: ["ضربته", "موتته", "شتمته"] }, type: 'proverb', difficulty: 2 },
  { text: "أنا غني وأحب", completions: { correct: "الهدية", wrong: ["العطية", "الصدقة", "الزينة"] }, type: 'proverb', difficulty: 1 },
  { text: "أنفخ يا شريم قال ما من", completions: { correct: "برطم", wrong: ["شفايف", "هواء", "فم"] }, type: 'proverb', difficulty: 1 },
  { text: "بصلة المحب", completions: { correct: "خروف", wrong: ["عسل", "سيل", "دواء"] }, type: 'proverb', difficulty: 0 },
  { text: "بكره النقبا تقابل", completions: { correct: "بعضها", wrong: ["أعداءها", "وجوهها", "الناس"] }, type: 'proverb', difficulty: 1 },
  { text: "بوس الأيادي", completions: { correct: "ذل", wrong: ["كبر", "عز", "فخر"] }, type: 'proverb', difficulty: 1 },
  { text: "تفاءلوا بالخير", completions: { correct: "تجدوه", wrong: ["تنالوه", "تحصدوه", "تروه"] }, type: 'wisdom', difficulty: 0 },
  { text: "تمسكن حتى", completions: { correct: "تمكن", wrong: ["تضرب", "تقوى", "تعرف"] }, type: 'proverb', difficulty: 0 },
  { text: "تيجي مع الهبل", completions: { correct: "دبل", wrong: ["جوز", "حلو", "طبل"] }, type: 'proverb', difficulty: 1 },
  { text: "ﺟا يكحلها", completions: { correct: "عماها", wrong: ["بجاها", "خربها", "قتلها"] }, type: 'proverb', difficulty: 0 },
  { text: "جت الحزينة تفرح ما لقتلهاش", completions: { correct: "مطرح", wrong: ["مكان", "فرح", "كرسي"] }, type: 'proverb', difficulty: 0 },
  { text: "حبك برج العقرب وأنا برج", completions: { correct: "الجدي", wrong: ["الثور", "الأسد", "الميزان"] }, type: 'proverb', difficulty: 1 },
  { text: "حبل المودة", completions: { correct: "موصول", wrong: ["مقطوع", "متين", "قوي"] }, type: 'saying', difficulty: 0 },
  { text: "حلم الفرح", completions: { correct: "بعيد", wrong: ["قريب", "طويل", "جميل"] }, type: 'saying', difficulty: 1 },
  { text: "حوت ياكل", completions: { correct: "حوت", wrong: ["سمك", "إنسان", "بحر"] }, type: 'proverb', difficulty: 0 },
  { text: "خيراً تعمل شراً", completions: { correct: "تلقى", wrong: ["تحصد", "تجد", "تشوف"] }, type: 'wisdom', difficulty: 0 },
  { text: "دخان بلا", completions: { correct: "نار", wrong: ["حطب", "نور", "شرار"] }, type: 'wisdom', difficulty: 0 },
  { text: "دخول الحمام مش زي", completions: { correct: "خروجه", wrong: ["قعدته", "نظافته", "حره"] }, type: 'proverb', difficulty: 0 },
  { text: "رضينا بالهم والهم مش راضي", completions: { correct: "بينا", wrong: ["بنا", "بحالنا", "فرحان"] }, type: 'proverb', difficulty: 0 },
  { text: "سبع صنايع والبخت", completions: { correct: "ضايع", wrong: ["مايل", "نايم", "قاعد"] }, type: 'proverb', difficulty: 0 },
  { text: "شامخ زي الجبل ما يهزك", completions: { correct: "ريح", wrong: ["مطر", "رعد", "شجر"] }, type: 'proverb', difficulty: 0 },
  { text: "عتاب الندل", completions: { correct: "اجتنابه", wrong: ["هروبه", "كرهه", "شتمه"] }, type: 'wisdom', difficulty: 1 },
  { text: "عصفور في الايد خير من عشرة على", completions: { correct: "الشجرة", wrong: ["السما", "الهواء", "الأرض"] }, type: 'proverb', difficulty: 0 },
  { text: "عطني ودنة وخذ", completions: { correct: "قرطها", wrong: ["كلها", "نصها", "قلبها"] }, type: 'proverb', difficulty: 2 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["إيديك", "نفسك", "طولك"] }, type: 'proverb', difficulty: 0 },
  { text: "عمر الدم ما يبقى", completions: { correct: "ميه", wrong: ["عصير", "شاي", "عرق"] }, type: 'proverb', difficulty: 0 },
  { text: "عمر الفار ما يكون", completions: { correct: "نجار", wrong: ["طباخ", "حداد", "خياط"] }, type: 'proverb', difficulty: 1 }
];
