import { ProverbData } from './types';
export const MEGA_PROVERBS_6: ProverbData[] = [
  { text: "أجود الخيل ما يرى", completions: { correct: "سائسه", wrong: ["ركابه", "لجامه", "لونه"] }, type: 'proverb', difficulty: 2 },
  { text: "أحلام", completions: { correct: "اليقظة", wrong: ["النوم", "الليل", "المحبيبن"] }, type: 'saying', difficulty: 1 },
  { text: "إذا بيتك من قزاز لا ترمي الناس بـ", completions: { correct: "حجارة", wrong: ["طوب", "ورد", "كلام"] }, type: 'proverb', difficulty: 0 },
  { text: "إذا حضر الماء بطل", completions: { correct: "التيمم", wrong: ["الوضوء", "الصلاة", "الطهارة"] }, type: 'wisdom', difficulty: 0 },
  { text: "إذا غلي اللحم الصبر", completions: { correct: "رخيص", wrong: ["غالي", "بلاش", "دواء"] }, type: 'proverb', difficulty: 1 },
  { text: "اركب الديك وشف فين", completions: { correct: "يوديك", wrong: ["يطير", "ينام", "يصقع"] }, type: 'proverb', difficulty: 2 },
  { text: "اسأل مجرب ولا تسأل", completions: { correct: "طبيب", wrong: ["حكيم", "شيخ", "عالم"] }, type: 'proverb', difficulty: 0 },
  { text: "اسألوه عن أبوه قال", completions: { correct: "خالي", wrong: ["عمي", "أخوي", "مدري"] }, type: 'proverb', difficulty: 1 },
  { text: "امسك خيطك ما يطير", completions: { correct: "طيرك", wrong: ["ورقك", "مالك", "حظك"] }, type: 'proverb', difficulty: 1 },
  { text: "أنا وأخوي على ابن عمي، وأنا وابن عمي على", completions: { correct: "الغريب", wrong: ["القريب", "العدو", "الجار"] }, type: 'proverb', difficulty: 0 },
  { text: "إن طاعك الزمان ولا", completions: { correct: "طعه", wrong: ["عصيه", "حاربه", "اهجره"] }, type: 'proverb', difficulty: 1 },
  { text: "إن كان حبيبك عسل لا تلحسه", completions: { correct: "كله", wrong: ["نصه", "ربعه", "شوي"] }, type: 'proverb', difficulty: 0 },
  { text: "أهلك لا تهلك", completions: { correct: "يا ولد", wrong: ["في الغربة", "عنهم", "منهم"] }, type: 'proverb', difficulty: 2 },
  { text: "بات في جوع ولا تبات في", completions: { correct: "دين", wrong: ["قهر", "حزن", "خوف"] }, type: 'wisdom', difficulty: 0 },
  { text: "بحصة بتسند", completions: { correct: "خابية", wrong: ["جرة", "حجر", "بيت"] }, type: 'proverb', difficulty: 0 },
  { text: "تعبت أربى ونسيت", completions: { correct: "الترباية", wrong: ["الدراسة", "التعب", "السهر"] }, type: 'proverb', difficulty: 1 },
  { text: "تكبر وتنسى", completions: { correct: "همومها", wrong: ["أيامها", "أوجاعها", "ألمها"] }, type: 'proverb', difficulty: 1 },
  { text: "تمسكن حتى", completions: { correct: "تمكن", wrong: ["تضرب", "تعرف", "تهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "ثوب العيرة ما", completions: { correct: "يدفي", wrong: ["يستر", "يغطي", "يحلي"] }, type: 'proverb', difficulty: 1 },
  { text: "جا يكحلها", completions: { correct: "عماها", wrong: ["بجاها", "خربها", "لعبها"] }, type: 'proverb', difficulty: 0 },
  { text: "جحا أولى بلحم", completions: { correct: "ثوره", wrong: ["كبشه", "أبوه", "طيره"] }, type: 'proverb', difficulty: 1 },
  { text: "جزاء", completions: { correct: "سنمار", wrong: ["الكافر", "الخائن", "الهارب"] }, type: 'saying', difficulty: 0 },
  { text: "حساب سرايا ما طابق حساب", completions: { correct: "قرايا", wrong: ["أرياف", "مدن", "حارات"] }, type: 'proverb', difficulty: 1 },
  { text: "حط إيدك في ماء", completions: { correct: "بارد", wrong: ["حار", "مالح", "حلو"] }, type: 'proverb', difficulty: 0 },
  { text: "حط بالخرج", completions: { correct: "ملح", wrong: ["سمن", "سكر", "ماء"] }, type: 'proverb', difficulty: 2 },
  { text: "خير الأمور", completions: { correct: "أوسطها", wrong: ["أولها", "آخرها", "أعلاها"] }, type: 'wisdom', difficulty: 0 },
  { text: "دخان بلا", completions: { correct: "نار", wrong: ["حطب", "نور", "ريح"] }, type: 'wisdom', difficulty: 0 },
  { text: "درهم وقاية خير من قنطار", completions: { correct: "علاج", wrong: ["دواء", "مريض", "أطباء"] }, type: 'wisdom', difficulty: 0 },
  { text: "ديل الكلب أبد ما", completions: { correct: "يتعدل", wrong: ["ينكسر", "ينعوج", "يوقف"] }, type: 'proverb', difficulty: 0 },
  { text: "راح خيطي في", completions: { correct: "ميضتي", wrong: ["بضاعتي", "طريقي", "شنطتي"] }, type: 'proverb', difficulty: 2 },
  { text: "راعي النصفين", completions: { correct: "كذاب", wrong: ["بخيل", "طماع", "سارق"] }, type: 'proverb', difficulty: 1 },
  { text: "زلة لسان ولا زلة", completions: { correct: "قدم", wrong: ["عقل", "قلب", "عين"] }, type: 'wisdom', difficulty: 1 },
  { text: "زي القطط تاكل", completions: { correct: "وتنكر", wrong: ["وتشرب", "وتنام", "وتهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "سبع صنايع والبخت", completions: { correct: "ضايع", wrong: ["مايل", "نايم", "قاعد"] }, type: 'proverb', difficulty: 0 },
  { text: "شامخ زي الجبل ما يهزك", completions: { correct: "ريح", wrong: ["شجر", "مطر", "رعد"] }, type: 'proverb', difficulty: 0 },
  { text: "ضربني وبكى سبقني و", completions: { correct: "اشتكى", wrong: ["بكى", "حكى", "رمى"] }, type: 'proverb', difficulty: 0 },
  { text: "طاسة ضايعة", completions: { correct: "فيها", wrong: ["عليها", "تحتها", "جنبها"] }, type: 'proverb', difficulty: 1 },
  { text: "طنش تعش", completions: { correct: "تنتعش", wrong: ["تستريح", "ترتاح", "تفرح"] }, type: 'proverb', difficulty: 0 },
  { text: "عطني ودنة وخذ", completions: { correct: "قرطها", wrong: ["نصها", "كلها", "عقلها"] }, type: 'proverb', difficulty: 2 },
  { text: "عمر الفار ما يكون", completions: { correct: "نجار", wrong: ["حداد", "طباخ", "سواق"] }, type: 'proverb', difficulty: 1 }
];
