import { ProverbData } from './types';
export const MEGA_PROVERBS_12: ProverbData[] = [
  { text: "اللي ما يعرفك ما", completions: { correct: "يثمنك", wrong: ["يقدرك", "يحترمك", "يهينك"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يخلي نفسه نخالة ياكله", completions: { correct: "الدجاج", wrong: ["البط", "الكلب", "القط"] }, type: 'proverb', difficulty: 1 },
  { text: "ما يجي من الغرب يسر", completions: { correct: "القلب", wrong: ["العين", "الخاطر", "النفس"] }, type: 'proverb', difficulty: 1 },
  { text: "الباب اللي مفتوح نصه", completions: { correct: "يصك", wrong: ["يفتح", "يكسر", "ينقفل"] }, type: 'proverb', difficulty: 2 },
  { text: "قالوا يا فرعون مين فرعنك قال مالقيت", completions: { correct: "من يردني", wrong: ["من ينصحني", "من يضربني", "من يفقهني"] }, type: 'proverb', difficulty: 1 },
  { text: "القرد بعين أمه", completions: { correct: "غزال", wrong: ["ذيب", "أسد", "بطل"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي يقرس الحية يخاف من", completions: { correct: "الحبل", wrong: ["الصوت", "الماء", "النار"] }, type: 'proverb', difficulty: 0 },
  { text: "أكل ومرعى وقلة", completions: { correct: "صنعة", wrong: ["نوم", "شغل", "فهم"] }, type: 'proverb', difficulty: 0 },
  { text: "عمر جزر البحر ما كسر", completions: { correct: "الصخر", wrong: ["الجبل", "الباب", "الموج"] }, type: 'proverb', difficulty: 2 },
  { text: "اللي يخجل من بنت عمه ما", completions: { correct: "يجيب ولاد", wrong: ["يتزوجها", "يفرح", "يبني بيت"] }, type: 'proverb', difficulty: 1 },
  { text: "أنت تريد وأنا أريد والله يفعل ما", completions: { correct: "يريد", wrong: ["يشاء", "يختار", "يحب"] }, type: 'wisdom', difficulty: 0 },
  { text: "ياما تحت السواهي", completions: { correct: "دواهي", wrong: ["مصايب", "أحزان", "أسرار"] }, type: 'proverb', difficulty: 0 },
  { text: "يا حافر حفرة السوء لا تعمق", completions: { correct: "مواسيها", wrong: ["أطرافها", "قاعها", "أساسها"] }, type: 'proverb', difficulty: 2 },
  { text: "حوت ياكل حوت وقليل الجهد", completions: { correct: "يموت", wrong: ["يعيش", "يهرب", "يغرق"] }, type: 'proverb', difficulty: 1 },
  { text: "شوية على الخال وشوية على", completions: { correct: "العم", wrong: ["الجد", "الأب", "الأخ"] }, type: 'proverb', difficulty: 1 },
  { text: "الناس في الناس والقرعة في مشط", completions: { correct: "الراس", wrong: ["الشعر", "الذهن", "الكلام"] }, type: 'proverb', difficulty: 1 },
  { text: "لو كان فيه خير ما رماه", completions: { correct: "الطير", wrong: ["الناس", "صاحبه", "الزمن"] }, type: 'proverb', difficulty: 0 },
  { text: "الضحك من غير سبب قلة", completions: { correct: "أدب", wrong: ["إيمان", "عقل", "حياء"] }, type: 'wisdom', difficulty: 0 },
  { text: "يا محلاها عيشة الفلاح", completions: { correct: "مرتاح", wrong: ["تعبان", "شقيان", "بسيط"] }, type: 'proverb', difficulty: 0 },
  { text: "إذا غلي اللحم عليك بـ", completions: { correct: "المرق", wrong: ["الفول", "الخضار", "الخبز"] }, type: 'proverb', difficulty: 1 },
  { text: "البقرة الحلوب خير من العجلة", completions: { correct: "العقيم", wrong: ["السريعة", "الكبيرة", "الصغيرة"] }, type: 'proverb', difficulty: 1 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["طولك", "إيديك", "ظهرك"] }, type: 'proverb', difficulty: 0 },
  { text: "من جد وجد ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نجح", "نال"] }, type: 'wisdom', difficulty: 0 },
  { text: "اللي ما يشوف من الغربال أعمى", completions: { correct: "البصر", wrong: ["القلب", "النظرة", "العين"] }, type: 'proverb', difficulty: 0 },
  { text: "رب بعيد أنفع من", completions: { correct: "قريب", wrong: ["صديق", "أخ", "جار"] }, type: 'wisdom', difficulty: 0 },
  { text: "يد الحر ميزان", completions: { correct: "الحق", wrong: ["الذهب", "الوزن", "العدل"] }, type: 'wisdom', difficulty: 1 },
  { text: "عشمتني بالحلق، خرمت أنا", completions: { correct: "وداني", wrong: ["قلبي", "إيدي", "أصبعي"] }, type: 'proverb', difficulty: 0 },
  { text: "ما يوقع إلا", completions: { correct: "الشاطر", wrong: ["الذكي", "الغبي", "الصغير"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ماله كبير يشتريله", completions: { correct: "كبير", wrong: ["غالي", "جديد", "أصيل"] }, type: 'proverb', difficulty: 0 },
  { text: "عضة أسد ولا نظرة", completions: { correct: "حسد", wrong: ["حقد", "كره", "غدر"] }, type: 'proverb', difficulty: 1 }
];
