import { ProverbData } from './types';
export const MEGA_PROVERBS_9: ProverbData[] = [
  { text: "اللي ايده في المية مش زي اللي ايده في", completions: { correct: "النار", wrong: ["الهواء", "الماء", "التراب"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي بيته من إزاز ما يحدفش الناس", completions: { correct: "بالطوب", wrong: ["بالحجر", "بالورد", "بالنار"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي تحسبه موسى يطلع", completions: { correct: "فرعون", wrong: ["هامان", "قارون", "نمرود"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي ما يعرفالصقر", completions: { correct: "يشويه", wrong: ["ياكله", "يربيه", "يصيده"] }, type: 'proverb', difficulty: 0 },
  { text: "أول الرقص", completions: { correct: "حنجلة", wrong: ["لعب", "فرح", "ضحك"] }, type: 'proverb', difficulty: 1 },
  { text: "الباب اللي يجيلك منه الريح سده", completions: { correct: "واستريح", wrong: ["وارتاح", "أقفله", "اكسره"] }, type: 'proverb', difficulty: 0 },
  { text: "القرد في عين أمه", completions: { correct: "غزال", wrong: ["أمير", "قمر", "أسد"] }, type: 'proverb', difficulty: 0 },
  { text: "النجار بابه", completions: { correct: "مخلع", wrong: ["مكسور", "حديد", "خشب"] }, type: 'proverb', difficulty: 0 },
  { text: "بصلة المحب", completions: { correct: "خروف", wrong: ["تفاحة", "سكر", "عسل"] }, type: 'proverb', difficulty: 1 },
  { text: "بعد ما شاب ودوه", completions: { correct: "الكتاب", wrong: ["المدرسة", "الجامعة", "البيت"] }, type: 'proverb', difficulty: 0 },
  { text: "جت الحزينة تفرح ما لقتلهاش", completions: { correct: "مطرح", wrong: ["مكان", "صاحب", "كرسي"] }, type: 'proverb', difficulty: 0 },
  { text: "حرّص ولا", completions: { correct: "تخون", wrong: ["تأمن", "تكذب", "تصيغ"] }, type: 'wisdom', difficulty: 1 },
  { text: "حلم القطط كله", completions: { correct: "فيران", wrong: ["لحمة", "لبن", "سمك"] }, type: 'proverb', difficulty: 0 },
  { text: "خالف", completions: { correct: "تعرف", wrong: ["تنجح", "تسلم", "تندم"] }, type: 'saying', difficulty: 0 },
  { text: "دخول الحمام مش زي", completions: { correct: "خروجه", wrong: ["نومه", "قعدته", "دفعته"] }, type: 'proverb', difficulty: 0 },
  { text: "رضينا بالهم والهم مش راضي", completions: { correct: "بينا", wrong: ["بحالنا", "فرحان", "موافق"] }, type: 'proverb', difficulty: 0 },
  { text: "زي القطط بسبع", completions: { correct: "أرواح", wrong: ["عيون", "أسنان", "رجول"] }, type: 'proverb', difficulty: 0 },
  { text: "شحاد ومشارط", completions: { correct: "على خبزاتنا", wrong: ["على فلوسنا", "على هدومنا", "على بيتنا"] }, type: 'proverb', difficulty: 1 },
  { text: "ضربني وبكى سبقني", completions: { correct: "واشتكى", wrong: ["وجرى", "وطلب", "وهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "طاسة ضايعة", completions: { correct: "فيها", wrong: ["عليها", "جنبها", "تحتها"] }, type: 'proverb', difficulty: 1 },
  { text: "ظل راجل ولا ظل", completions: { correct: "حيطة", wrong: ["شجرة", "جبل", "بيت"] }, type: 'proverb', difficulty: 1 },
  { text: "عصفور في الايد أحسن من عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "في الجو"] }, type: 'proverb', difficulty: 0 },
  { text: "عمر الفار ما يكون", completions: { correct: "نجار", wrong: ["خياط", "حداد", "كهربائي"] }, type: 'proverb', difficulty: 1 },
  { text: "غاب القط العب يا", completions: { correct: "فار", wrong: ["كلب", "عصفور", "قرد"] }, type: 'proverb', difficulty: 0 },
  { text: "في التأني السلامة وفي العجلة", completions: { correct: "الندامة", wrong: ["الخسارة", "الموت", "التعب"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل فولة ولها", completions: { correct: "كيال", wrong: ["شراي", "أكال", "بياع"] }, type: 'proverb', difficulty: 0 },
  { text: "لا تذم ولا تشكر إلا بعد", completions: { correct: "ست أشهر", wrong: ["سنة", "سبع أيام", "شهر"] }, type: 'wisdom', difficulty: 1 },
  { text: "مراية الحب", completions: { correct: "عميا", wrong: ["كذابة", "نصابة", "مكسورة"] }, type: 'proverb', difficulty: 0 },
  { text: "من شاف بلاوي الناس هانت عليه", completions: { correct: "بلوته", wrong: ["مشكلته", "مصيبته", "حياته"] }, type: 'wisdom', difficulty: 0 },
  { text: "هم يبكي وهم", completions: { correct: "يضحك", wrong: ["يفرح", "يسعد", "يصرخ"] }, type: 'proverb', difficulty: 0 }
];
