import { ProverbData } from './types';
export const MEGA_PROVERBS_10: ProverbData[] = [
  { text: "اللي ماله أول ماله", completions: { correct: "تالي", wrong: ["ثاني", "أخير", "حالي"] }, type: 'proverb', difficulty: 0 },
  { text: "رب صدفة خير من ألف", completions: { correct: "ميعاد", wrong: ["لقاء", "موعد", "سنة"] }, type: 'wisdom', difficulty: 0 },
  { text: "أجود من حاتم", completions: { correct: "الطائي", wrong: ["العربي", "البطل", "السخي"] }, type: 'saying', difficulty: 1 },
  { text: "مسمار في", completions: { correct: "لوح", wrong: ["حائط", "خشب", "باب"] }, type: 'proverb', difficulty: 1 },
  { text: "أكذب من مسيلمة", completions: { correct: "الكذاب", wrong: ["المنافق", "الخائن", "النصاب"] }, type: 'saying', difficulty: 1 },
  { text: "دخان بلا", completions: { correct: "نار", wrong: ["حطب", "نور", "ريح"] }, type: 'wisdom', difficulty: 0 },
  { text: "كالباحث عن إبرة في كومة", completions: { correct: "قش", wrong: ["تراب", "رمل", "حديد"] }, type: 'proverb', difficulty: 0 },
  { text: "يضرب عصفورين بـ", completions: { correct: "حجر", wrong: ["سهم", "عصا", "نار"] }, type: 'proverb', difficulty: 0 },
  { text: "الطيور على أشكالها", completions: { correct: "تقع", wrong: ["تطير", "تنام", "تغرد"] }, type: 'wisdom', difficulty: 0 },
  { text: "إذا عرف السبب بطل", completions: { correct: "العجب", wrong: ["الخوف", "الغضب", "السحر"] }, type: 'wisdom', difficulty: 0 },
  { text: "أعط الصباح فرصته لكي يغير", completions: { correct: "الأحوال", wrong: ["الأيام", "الليالي", "الأزمان"] }, type: 'wisdom', difficulty: 1 },
  { text: "الأيام دول، يوم لك ويوم", completions: { correct: "عليك", wrong: ["معك", "ضدك", "فيك"] }, type: 'wisdom', difficulty: 0 },
  { text: "البياض نصف", completions: { correct: "الجمال", wrong: ["الحسن", "الكمال", "البهاء"] }, type: 'saying', difficulty: 1 },
  { text: "الجزاء من جنس", completions: { correct: "العمل", wrong: ["الفعل", "القول", "الحركة"] }, type: 'wisdom', difficulty: 0 },
  { text: "الحب أعمى", completions: { correct: "يقولون", wrong: ["كالأعمى", "لا يرى", "مكسور"] }, type: 'saying', difficulty: 1 },
  { text: "الصبر مفتاح", completions: { correct: "الفرج", wrong: ["الأمل", "النجاح", "الكسب"] }, type: 'wisdom', difficulty: 0 },
  { text: "الصيت ولا", completions: { correct: "الغنى", wrong: ["الفقر", "السلطان", "المال"] }, type: 'proverb', difficulty: 0 },
  { text: "الضرورات تبيح", completions: { correct: "المحظورات", wrong: ["المعاصي", "الذنوب", "الشهوات"] }, type: 'wisdom', difficulty: 0 },
  { text: "العقل السليم في الجسم", completions: { correct: "السليم", wrong: ["الصحيح", "القوي", "الكبير"] }, type: 'wisdom', difficulty: 0 },
  { text: "الغرقان يتعلق بـ", completions: { correct: "قشة", wrong: ["حبل", "غصن", "صخرة"] }, type: 'proverb', difficulty: 0 },
  { text: "الغايب حجته", completions: { correct: "معه", wrong: ["وراه", "عنده", "فيه"] }, type: 'proverb', difficulty: 0 },
  { text: "الغالي ثمنه", completions: { correct: "فيه", wrong: ["معه", "غالي", "كثير"] }, type: 'proverb', difficulty: 0 },
  { text: "الفاضي يعمل", completions: { correct: "قاضي", wrong: ["محامي", "دكتور", "وزير"] }, type: 'proverb', difficulty: 1 },
  { text: "القرد في عين أمه", completions: { correct: "غزال", wrong: ["قمر", "أسد", "بطل"] }, type: 'proverb', difficulty: 0 },
  { text: "الكذب ملح", completions: { correct: "الرجال", wrong: ["النساء", "الأطفال", "الحياة"] }, type: 'proverb', difficulty: 2 },
  { text: "الكلمة الطيبة", completions: { correct: "صدقة", wrong: ["حسنة", "نور", "رحمة"] }, type: 'wisdom', difficulty: 0 },
  { text: "اللي أوله شرط آخره", completions: { correct: "نور", wrong: ["ظلام", "راحة", "سلام"] }, type: 'proverb', difficulty: 0 },
  { text: "اللي ما يعرفك يجهلك", completions: { correct: "ويهمك", wrong: ["ويظلمك", "ويتركك", "ويكرهك"] }, type: 'proverb', difficulty: 1 },
  { text: "اللي يحسب الحسابات في الهوى", completions: { correct: "يضيع", wrong: ["يطير", "يرتاح", "يموت"] }, type: 'proverb', difficulty: 2 },
  { text: "اللي يخاف من العفريت", completions: { correct: "يطلع له", wrong: ["ياكله", "ينام", "يهرب"] }, type: 'proverb', difficulty: 0 },
  { text: "إبعد عن الشر", completions: { correct: "وغنيله", wrong: ["وارتاح", "واسكت", "وتخيل"] }, type: 'proverb', difficulty: 0 },
  { text: "إدي العيش لخبازه ولو أكل", completions: { correct: "نصه", wrong: ["كله", "ربعه", "شوي"] }, type: 'proverb', difficulty: 0 },
  { text: "إذا أنت أكرمت الكريم ملكته، وإن أنت أكرمت اللئيم", completions: { correct: "تمردا", wrong: ["تكبرا", "تنكرا", "تجبرا"] }, type: 'wisdom', difficulty: 1 },
  { text: "إياك أعني واسمعي يا", completions: { correct: "جارة", wrong: ["مرة", "حرمة", "أميرة"] }, type: 'proverb', difficulty: 0 },
  { text: "أي شيء زاد عن حده انقلب", completions: { correct: "ضده", wrong: ["عكسه", "نحسه", "شره"] }, type: 'wisdom', difficulty: 0 },
  { text: "بطيخ يكسر", completions: { correct: "بعضه", wrong: ["نفسه", "قشره", "جاره"] }, type: 'proverb', difficulty: 2 },
  { text: "بيضرب في الميت", completions: { correct: "حرام", wrong: ["وجع", "تعب", "ألم"] }, type: 'proverb', difficulty: 0 },
  { text: "تفاءلوا بالخير", completions: { correct: "تجدوه", wrong: ["تلقوه", "تنالوه", "تحصدوه"] }, type: 'wisdom', difficulty: 0 },
  { text: "جت الحزينة تفرح ما لقتلهاش", completions: { correct: "مطرح", wrong: ["مكان", "كرسي", "شريك"] }, type: 'proverb', difficulty: 0 },
  { text: "حاميها", completions: { correct: "حراميها", wrong: ["سارقها", "حارسها", "قاضيها"] }, type: 'proverb', difficulty: 0 },
  { text: "حبل الكذب", completions: { correct: "قصير", wrong: ["طويل", "مردود", "ضعيف"] }, type: 'wisdom', difficulty: 0 },
  { text: "حِفْظُ اللسانِ راحةُ", completions: { correct: "الإنسانِ", wrong: ["الأبدان", "الأوطان", "الأذهان"] }, type: 'wisdom', difficulty: 1 },
  { text: "خير الكلام ما قل", completions: { correct: "ودل", wrong: ["وجل", "وعز", "ونفع"] }, type: 'wisdom', difficulty: 0 },
  { text: "درهم وقاية خير من قنطار", completions: { correct: "علاج", wrong: ["دواء", "مريض", "ألم"] }, type: 'wisdom', difficulty: 0 },
  { text: "ديل الكلب عمره ما", completions: { correct: "يتعدل", wrong: ["ينكسر", "يجلس", "يفهم"] }, type: 'proverb', difficulty: 0 },
  { text: "رجعت حليمة لعادتها", completions: { correct: "القديمة", wrong: ["الأولى", "السيئة", "المجنونة"] }, type: 'proverb', difficulty: 0 },
  { text: "رضا الناس غاية لا", completions: { correct: "تدرك", wrong: ["تعرف", "تصل", "تنتهي"] }, type: 'wisdom', difficulty: 0 },
  { text: "سبق السيف", completions: { correct: "العذل", wrong: ["الدم", "الوقت", "الندم"] }, type: 'saying', difficulty: 2 },
  { text: "شر البلية ما", completions: { correct: "يضحك", wrong: ["يبكي", "يفرح", "يقتل"] }, type: 'wisdom', difficulty: 0 },
  { text: "طاسة ضايعة", completions: { correct: "فيها", wrong: ["تحتها", "وراها", "منها"] }, type: 'proverb', difficulty: 2 },
  { text: "عتاب الندل", completions: { correct: "اجتنابه", wrong: ["شتمه", "ضربه", "إهماله"] }, type: 'wisdom', difficulty: 1 },
  { text: "عذر أقبح من", completions: { correct: "ذنب", wrong: ["فعل", "قول", "جريمة"] }, type: 'wisdom', difficulty: 0 },
  { text: "على قد لحافك مد", completions: { correct: "رجليك", wrong: ["إيديك", "طولك", "نفسك"] }, type: 'proverb', difficulty: 0 },
  { text: "عند الامتحان يكرم المرء أو", completions: { correct: "يهان", wrong: ["ينجح", "يفشل", "يظلم"] }, type: 'wisdom', difficulty: 0 },
  { text: "عصفور في اليد ولا عشرة على", completions: { correct: "الشجرة", wrong: ["السطح", "الأرض", "الحبل"] }, type: 'proverb', difficulty: 0 },
  { text: "فاقد الشيء لا", completions: { correct: "يعطيه", wrong: ["يملكه", "يفقده", "ياخذه"] }, type: 'wisdom', difficulty: 0 },
  { text: "في التأني السلامة وفي العجلة", completions: { correct: "الندامة", wrong: ["الخسارة", "السقوط", "الخطأ"] }, type: 'wisdom', difficulty: 0 },
  { text: "كل تأخيرة وفيها", completions: { correct: "خيرة", wrong: ["شر", "عبرة", "ندامة"] }, type: 'proverb', difficulty: 0 },
  { text: "كل سر جاوز الاثنين", completions: { correct: "شاع", wrong: ["ضاع", "مات", "ظهر"] }, type: 'wisdom', difficulty: 1 },
  { text: "لبس البوصة تبقى", completions: { correct: "عروسة", wrong: ["حلوة", "زينة", "فلة"] }, type: 'proverb', difficulty: 0 },
  { text: "لو تجري جري الوحوش غير رزقك ما", completions: { correct: "تحوش", wrong: ["تاخذ", "تمسك", "تشوف"] }, type: 'wisdom', difficulty: 0 },
  { text: "ما كل ما يتمنى المرء يدركه تجري الرياح بما لا تشتهي", completions: { correct: "السفن", wrong: ["الأسماك", "الطيور", "الغيوم"] }, type: 'wisdom', difficulty: 0 },
  { text: "ما يقع إلا", completions: { correct: "الشاطر", wrong: ["الكبير", "الغبي", "الصغير"] }, type: 'proverb', difficulty: 0 },
  { text: "مراية الحب", completions: { correct: "عميا", wrong: ["كذابة", "مكسورة", "نصابة"] }, type: 'proverb', difficulty: 0 },
  { text: "من برا هالله هالله ومن جوا يعلم", completions: { correct: "الله", wrong: ["الناس", "الشيطان", "الخلق"] }, type: 'proverb', difficulty: 0 },
  { text: "من جد وجد ومن زرع", completions: { correct: "حصد", wrong: ["أكل", "نام", "نجح"] }, type: 'wisdom', difficulty: 0 },
  { text: "من حفر حفرة لأخيه وقع", completions: { correct: "فيها", wrong: ["عليها", "بها", "تحتها"] }, type: 'wisdom', difficulty: 0 },
  { text: "من خاف", completions: { correct: "سلم", wrong: ["مات", "هرب", "نام"] }, type: 'wisdom', difficulty: 0 },
  { text: "من طلب العلا سهر", completions: { correct: "الليالي", wrong: ["النهار", "الفجر", "طويلاً"] }, type: 'wisdom', difficulty: 0 },
  { text: "هم يبكي وهم", completions: { correct: "يضحك", wrong: ["يفرح", "يحزن", "يسعد"] }, type: 'proverb', difficulty: 0 }
];
